insert into Acquirente (CF, Nome, Nazione, Città, Via, Civico) values ('CJWXVI75K97O770Z', 'Terencio', 'United States', 'Salt Lake City', 'Comanche', '7700');
insert into Acquirente (CF, Nome, Nazione, Città, Via, Civico) values ('AVGOIN39B71A372L', 'Essie', 'Indonesia', 'Dasanlian Lauk', 'Caliangt', '71445');
insert into Acquirente (CF, Nome, Nazione, Città, Via, Civico) values ('MLFHXV46E30O654L', 'Gilberto', 'Ukraine', 'Rokytne', 'Drewry', '21078');
insert into Acquirente (CF, Nome, Nazione, Città, Via, Civico) values ('MRFVNW64L86M192G', 'Vinita', 'Peru', 'Huanchaco', 'Union', '2');
insert into Acquirente (CF, Nome, Nazione, Città, Via, Civico) values ('ELTAIO04A49G866C', 'Luciana', 'Portugal', 'Portelinha', 'Cottonwood', '943');
insert into Acquirente (CF, Nome, Nazione, Città, Via, Civico) values ('INDCTE42Y17P762V', 'Shanie', 'Tajikistan', 'Obigarm', 'Chinook', '54');
insert into Acquirente (CF, Nome, Nazione, Città, Via, Civico) values ('DAKRMQ02Q92T379V', 'Rab', 'Colombia', 'Ariguaní', 'Express', '03');
insert into Acquirente (CF, Nome, Nazione, Città, Via, Civico) values ('AVCOUE99U68N227I', 'Katalin', 'China', 'Dashi', 'Jenna', '723');
insert into Acquirente (CF, Nome, Nazione, Città, Via, Civico) values ('DPLNGW14F22B788P', 'Daphene', 'Uruguay', 'Durazno', 'Merry', '22181');
insert into Acquirente (CF, Nome, Nazione, Città, Via, Civico) values ('OUBDSQ40E91N474L', 'Drona', 'United States', 'Columbus', 'Jay', '18342');
insert into Acquirente (CF, Nome, Nazione, Città, Via, Civico) values ('JULGBD78U32G348M', 'Maryellen', 'China', 'Xiaozhi', 'Maple Wood', '41');
insert into Acquirente (CF, Nome, Nazione, Città, Via, Civico) values ('RZEBKN50I75E721Z', 'Briano', 'France', 'Paris 11', 'Hanson', '8');
insert into Acquirente (CF, Nome, Nazione, Città, Via, Civico) values ('NARVQT95X88Z566S', 'Purcell', 'China', 'Nankou', 'Colorado', '71067');
insert into Acquirente (CF, Nome, Nazione, Città, Via, Civico) values ('YBORFQ16W63N987T', 'Tobiah', 'Canada', 'Salaberry-de-Valleyfield', 'Di Loreto', '769');
insert into Acquirente (CF, Nome, Nazione, Città, Via, Civico) values ('YSFHNX42Y05R850D', 'Meredith', 'Vietnam', 'Quán Hàu', 'Jenna', '33');
insert into Acquirente (CF, Nome, Nazione, Città, Via, Civico) values ('FYAKJL54I85Q628W', 'Alexandra', 'Indonesia', 'Subulussalam', '1st', '62980');
insert into Acquirente (CF, Nome, Nazione, Città, Via, Civico) values ('PQGELO38P79B350H', 'Cord', 'Afghanistan', 'Qarchī Gak', 'Barnett', '58605');
insert into Acquirente (CF, Nome, Nazione, Città, Via, Civico) values ('KMTZSP21S19M498M', 'Amandie', 'Sweden', 'Nybro', 'Pawling', '31');
insert into Acquirente (CF, Nome, Nazione, Città, Via, Civico) values ('WYLIPR44J46D615Q', 'Jordon', 'Liberia', 'Buchanan', 'Crownhardt', '0');
insert into Acquirente (CF, Nome, Nazione, Città, Via, Civico) values ('NJTPUB51V14R776B', 'Farra', 'Sweden', 'Skene', 'Farwell', '542');
insert into Acquirente (CF, Nome, Nazione, Città, Via, Civico) values ('NDLUCQ13W52W823O', 'Tuesday', 'Canada', 'Inuvik', 'International', '38214');
insert into Acquirente (CF, Nome, Nazione, Città, Via, Civico) values ('AXOHJG07F50J933M', 'Torie', 'Turkmenistan', 'Tejen', 'Scott', '7795');
insert into Acquirente (CF, Nome, Nazione, Città, Via, Civico) values ('VYMPFN25U94Y729E', 'Olin', 'Latvia', 'Iecava', 'Packers', '6191');
insert into Acquirente (CF, Nome, Nazione, Città, Via, Civico) values ('RAILYN20V92Q723A', 'Andeee', 'China', 'Laxiong', 'Veith', '42');
insert into Acquirente (CF, Nome, Nazione, Città, Via, Civico) values ('TCRFZS73L27N235Z', 'Christophe', 'Brazil', 'Pontes e Lacerda', 'Jenna', '88184');
insert into Acquirente (CF, Nome, Nazione, Città, Via, Civico) values ('MHAQFI37H28U661I', 'Farlie', 'Jordan', 'Al Kittah', 'Sloan', '6705');
insert into Acquirente (CF, Nome, Nazione, Città, Via, Civico) values ('JRBVIQ23P17A981T', 'Pammy', 'Brazil', 'Andradina', 'Hoard', '482');
insert into Acquirente (CF, Nome, Nazione, Città, Via, Civico) values ('OZUGJV98G14U458V', 'Lazaro', 'Czech Republic', 'Kozmice', 'Daystar', '60103');
insert into Acquirente (CF, Nome, Nazione, Città, Via, Civico) values ('ISDBTV10D86U364I', 'Bianka', 'Russia', 'Blagodatnoye', 'Melvin', '821');
insert into Acquirente (CF, Nome, Nazione, Città, Via, Civico) values ('RJHLQA33O49V146H', 'North', 'China', 'Shangshuai', 'Service', '57');
insert into Acquirente (CF, Nome, Nazione, Città, Via, Civico) values ('ZOLEIK97I41Z558Y', 'Lavinia', 'Turkmenistan', 'Türkmenbaşy', 'Bluejay', '4');
insert into Acquirente (CF, Nome, Nazione, Città, Via, Civico) values ('ADROVL45T44M509D', 'Llewellyn', 'Gabon', 'Fougamou', 'Chinook', '9');
insert into Acquirente (CF, Nome, Nazione, Città, Via, Civico) values ('MTPDKW50E99C357T', 'Euphemia', 'Poland', 'Skarbimierz Osiedle', 'Michigan', '6893');
insert into Acquirente (CF, Nome, Nazione, Città, Via, Civico) values ('EJWAIH01E10K907P', 'Hedvig', 'China', 'Daqiao', 'Bluestem', '431');
insert into Acquirente (CF, Nome, Nazione, Città, Via, Civico) values ('XLHORE99Q56K969T', 'Ede', 'Russia', 'Vidyayevo', 'Nova', '531');
insert into Acquirente (CF, Nome, Nazione, Città, Via, Civico) values ('HKTIWD87M28H697V', 'Chiquita', 'Panama', 'Los Algarrobos', 'Golf Course', '233');
insert into Acquirente (CF, Nome, Nazione, Città, Via, Civico) values ('ASEONX67S98M916E', 'Mortimer', 'Japan', 'Hiji', '4th', '0753');
insert into Acquirente (CF, Nome, Nazione, Città, Via, Civico) values ('ZKAHSL01P63L002M', 'Trixie', 'Japan', 'Sasaguri', 'Mitchell', '498');
insert into Acquirente (CF, Nome, Nazione, Città, Via, Civico) values ('EWKQGZ17F74X222N', 'Neda', 'Thailand', 'Lat Lum Kaeo', 'Sauthoff', '997');
insert into Acquirente (CF, Nome, Nazione, Città, Via, Civico) values ('HNRZJV87O80G262T', 'Sinclare', 'Thailand', 'Bang Nam Priao', 'Maple Wood', '530');
insert into Acquirente (CF, Nome, Nazione, Città, Via, Civico) values ('OJCXYS67J46I803L', 'Cecil', 'Philippines', 'Jagna', 'Logan', '54080');
insert into Acquirente (CF, Nome, Nazione, Città, Via, Civico) values ('PJDYWL58U69J587W', 'Emmerich', 'Philippines', 'Madalum', 'Hauk', '11025');
insert into Acquirente (CF, Nome, Nazione, Città, Via, Civico) values ('JLVAPQ38T41A891P', 'Ferdinande', 'Philippines', 'Bulawin', 'Warner', '16334');
insert into Acquirente (CF, Nome, Nazione, Città, Via, Civico) values ('DGNEVR17W09Y796O', 'Aurelie', 'Syria', 'Al Manşūrah', 'Crescent Oaks', '62');
insert into Acquirente (CF, Nome, Nazione, Città, Via, Civico) values ('STHYZC13X52S041C', 'Zsazsa', 'France', 'Aix-en-Provence', 'Fulton', '53');
insert into Acquirente (CF, Nome, Nazione, Città, Via, Civico) values ('ZWPAGM10M08D347T', 'Amerigo', 'Qatar', 'Umm Şalāl ‘Alī', 'Porter', '3');
insert into Acquirente (CF, Nome, Nazione, Città, Via, Civico) values ('NVEKYX27O37F254S', 'Frankie', 'United States', 'Erie', 'Golf View', '20567');
insert into Acquirente (CF, Nome, Nazione, Città, Via, Civico) values ('WXPBUA62P61G788N', 'Klemens', 'New Zealand', 'Taipa', 'Anniversary', '46794');
insert into Acquirente (CF, Nome, Nazione, Città, Via, Civico) values ('DSYCFB64D98Y457D', 'Caren', 'China', 'Wudangshan', 'Troy', '20782');
insert into Acquirente (CF, Nome, Nazione, Città, Via, Civico) values ('EDPANR00I12A043H', 'Adelaida', 'China', 'Jingping', 'Parkside', '67896');