insert into Dipendente (CF, Nome, Cognome, Mansione, Nazione, Città, Via, Civico) values ('RYFWZO66L14L336W', 'Farica', 'Meynell', 'Meccanico', 'Ukraine', 'Terny', '5th', '803');
insert into Dipendente (CF, Nome, Cognome, Mansione, Nazione, Città, Via, Civico) values ('IKGRTQ94H83A629Q', 'D''arcy', 'Spurier', 'Impiegato', 'Indonesia', 'Pondokaso', 'Schiller', '0117');
insert into Dipendente (CF, Nome, Cognome, Mansione, Nazione, Città, Via, Civico) values ('TIPWMQ35E19R424U', 'Grady', 'Skase', 'Dirigente', 'Vietnam', 'Quỳ Châu', 'Lukken', '73344');
insert into Dipendente (CF, Nome, Cognome, Mansione, Nazione, Città, Via, Civico) values ('GEQMOH78M92C221Q', 'Felicity', 'Belz', 'Dirigente', 'Poland', 'Józefów', 'Truax', '33');
insert into Dipendente (CF, Nome, Cognome, Mansione, Nazione, Città, Via, Civico) values ('RTIBLG42H44E431C', 'Saxe', 'Mengue', 'Impiegato', 'France', 'Boulogne-sur-Mer', 'Lukken', '2');
insert into Dipendente (CF, Nome, Cognome, Mansione, Nazione, Città, Via, Civico) values ('VOBNUF63N53R914Y', 'Dieter', 'O''Kynsillaghe', 'Meccanico', 'Serbia', 'Seleuš', 'Springs', '6047');
insert into Dipendente (CF, Nome, Cognome, Mansione, Nazione, Città, Via, Civico) values ('KYWTIC72Y14C857P', 'Brigit', 'Matusevich', 'Impiegato', 'Ukraine', 'Banyliv', 'Main', '3');
insert into Dipendente (CF, Nome, Cognome, Mansione, Nazione, Città, Via, Civico) values ('ZSCQHT02T02K420Z', 'Manda', 'Skully', 'Impiegato', 'China', 'Hongtu', '3rd', '20114');
insert into Dipendente (CF, Nome, Cognome, Mansione, Nazione, Città, Via, Civico) values ('NUYBQZ04M81Z337X', 'Winnie', 'Goring', 'Dirigente', 'Finland', 'Rautjärvi', 'Charing Cross', '7');
insert into Dipendente (CF, Nome, Cognome, Mansione, Nazione, Città, Via, Civico) values ('UXAWKM77U99Q663Y', 'Valentine', 'Shillaker', 'Dirigente', 'Philippines', 'Sabang', 'Mcbride', '85');
insert into Dipendente (CF, Nome, Cognome, Mansione, Nazione, Città, Via, Civico) values ('QWICBT74L42A035V', 'Othello', 'Hamlyn', 'Impiegato', 'Tanzania', 'Pangani', 'Forest', '95');
insert into Dipendente (CF, Nome, Cognome, Mansione, Nazione, Città, Via, Civico) values ('QZHJDT68K45I361B', 'Aryn', 'Golling', 'Impiegato', 'Honduras', 'Baja Mar', 'Blaine', '72');
insert into Dipendente (CF, Nome, Cognome, Mansione, Nazione, Città, Via, Civico) values ('DNVTBH29S71X928C', 'Christa', 'Oldham', 'Meccanico', 'Thailand', 'Pathum Thani', 'Kensington', '9');
insert into Dipendente (CF, Nome, Cognome, Mansione, Nazione, Città, Via, Civico) values ('IOYZHE91D51V715M', 'Randy', 'Saffell', 'Meccanico', 'Indonesia', 'Setono', 'Eggendart', '5648');
insert into Dipendente (CF, Nome, Cognome, Mansione, Nazione, Città, Via, Civico) values ('APMCWL81E20I197F', 'Roseanna', 'Vassman', 'Dirigente', 'Russia', 'Solnechnogorsk', 'Towne', '5263');
insert into Dipendente (CF, Nome, Cognome, Mansione, Nazione, Città, Via, Civico) values ('WTDZCP70I28O134Q', 'Viola', 'Sulter', 'Impiegato', 'China', 'Shangyong', 'Meadow Vale', '7');
insert into Dipendente (CF, Nome, Cognome, Mansione, Nazione, Città, Via, Civico) values ('SOXNKL53G37Y946Y', 'Ave', 'Siemantel', 'Dirigente', 'Poland', 'Pszczyna', 'Manley', '4');
insert into Dipendente (CF, Nome, Cognome, Mansione, Nazione, Città, Via, Civico) values ('DWBRJN23Y91H298U', 'Lynnea', 'Le Quesne', 'Meccanico', 'Poland', 'Cielmice', 'Merry', '79');
insert into Dipendente (CF, Nome, Cognome, Mansione, Nazione, Città, Via, Civico) values ('RMJTVX23B87U509L', 'Reg', 'Kewish', 'Meccanico', 'Japan', 'Kamimaruko', 'Golf View', '82');
insert into Dipendente (CF, Nome, Cognome, Mansione, Nazione, Città, Via, Civico) values ('EFYQSL82C25A429C', 'Leigha', 'Coton', 'Impiegato', 'Peru', 'Urasqui', 'Lakewood', '89540');
insert into Dipendente (CF, Nome, Cognome, Mansione, Nazione, Città, Via, Civico) values ('MHRBAL70T50O514A', 'Marena', 'Albert', 'Meccanico', 'Portugal', 'Amadora', 'Evergreen', '45');
insert into Dipendente (CF, Nome, Cognome, Mansione, Nazione, Città, Via, Civico) values ('AHECPQ36M17W279C', 'Bernarr', 'Gay', 'Meccanico', 'Honduras', 'El Triunfo de la Cruz', 'Glacier Hill', '40785');
insert into Dipendente (CF, Nome, Cognome, Mansione, Nazione, Città, Via, Civico) values ('INXVHS11K30G871X', 'Candice', 'Whinray', 'Meccanico', 'Indonesia', 'Cempa', 'Chinook', '00');
insert into Dipendente (CF, Nome, Cognome, Mansione, Nazione, Città, Via, Civico) values ('GSONYP79O27P538Y', 'Greg', 'Ogers', 'Meccanico', 'Russia', 'Kangalassy', 'Kinsman', '28758');
insert into Dipendente (CF, Nome, Cognome, Mansione, Nazione, Città, Via, Civico) values ('MAZDYU97D71G905O', 'Edita', 'Trowle', 'Meccanico', 'Poland', 'Lipnik', 'Coleman', '1375');
insert into Dipendente (CF, Nome, Cognome, Mansione, Nazione, Città, Via, Civico) values ('QIDUMZ12Y07E399M', 'Ivory', 'Lefeaver', 'Meccanico', 'Portugal', 'Quintas', 'Sunbrook', '7041');
insert into Dipendente (CF, Nome, Cognome, Mansione, Nazione, Città, Via, Civico) values ('IMYJBW63Q52F610X', 'Drucie', 'Dalley', 'Meccanico', 'Poland', 'Czechowice-Dziedzice', 'Northwestern', '32294');
insert into Dipendente (CF, Nome, Cognome, Mansione, Nazione, Città, Via, Civico) values ('MKQGEX22M93S413X', 'Isidoro', 'Giovannardi', 'Impiegato', 'Russia', 'Kastornoye', 'Banding', '35');
insert into Dipendente (CF, Nome, Cognome, Mansione, Nazione, Città, Via, Civico) values ('SYIONR88Y70A893K', 'Margy', 'Tupp', 'Impiegato', 'Democratic Republic of the Congo', 'Buta', 'Debs', '817');
insert into Dipendente (CF, Nome, Cognome, Mansione, Nazione, Città, Via, Civico) values ('BXGSHP58P31U870P', 'Jessamyn', 'Heeps', 'Meccanico', 'China', 'Zhangjiahe', 'Tony', '51565');
insert into Dipendente (CF, Nome, Cognome, Mansione, Nazione, Città, Via, Civico) values ('DTVECN37B23Z032C', 'Conrad', 'McClymond', 'Dirigente', 'Morocco', 'Tanalt', '3rd', '3');
insert into Dipendente (CF, Nome, Cognome, Mansione, Nazione, Città, Via, Civico) values ('DXGNCJ47Z65D161K', 'Elwyn', 'Kestian', 'Meccanico', 'Brazil', 'Aparecida do Taboado', 'Cambridge', '4030');
insert into Dipendente (CF, Nome, Cognome, Mansione, Nazione, Città, Via, Civico) values ('CZRPSQ04Z64K115K', 'Odey', 'Durdy', 'Dirigente', 'Argentina', 'Pérez', 'Manufacturers', '1');
insert into Dipendente (CF, Nome, Cognome, Mansione, Nazione, Città, Via, Civico) values ('KMOCHU12C59H980B', 'Cory', 'Creaser', 'Meccanico', 'Brazil', 'São Gonçalo do Sapucaí', 'Colorado', '656');
insert into Dipendente (CF, Nome, Cognome, Mansione, Nazione, Città, Via, Civico) values ('JYEHXA16K09X859Y', 'Carmine', 'Weatherley', 'Meccanico', 'Portugal', 'Pereiras', 'Glendale', '7');
insert into Dipendente (CF, Nome, Cognome, Mansione, Nazione, Città, Via, Civico) values ('KNMGQV35V94C916U', 'Kristal', 'Janko', 'Meccanico', 'Philippines', 'Villa Verde', 'Schlimgen', '43');
insert into Dipendente (CF, Nome, Cognome, Mansione, Nazione, Città, Via, Civico) values ('HXELRU57Q85M482L', 'Kerr', 'O'' Driscoll', 'Dirigente', 'Indonesia', 'Langkaplancar', 'Emmet', '99337');
insert into Dipendente (CF, Nome, Cognome, Mansione, Nazione, Città, Via, Civico) values ('KLMWSZ71O00A119G', 'Raeann', 'Dwyer', 'Meccanico', 'Indonesia', 'Cileuya', 'Fallview', '6');
insert into Dipendente (CF, Nome, Cognome, Mansione, Nazione, Città, Via, Civico) values ('XJTFLQ00O22Z079B', 'Jedd', 'Viger', 'Dirigente', 'Sweden', 'Floda', 'Dexter', '0462');
insert into Dipendente (CF, Nome, Cognome, Mansione, Nazione, Città, Via, Civico) values ('OSMBVJ16J62B083M', 'Ced', 'Pawley', 'Meccanico', 'Sweden', 'Borlänge', 'Dexter', '43649');
insert into Dipendente (CF, Nome, Cognome, Mansione, Nazione, Città, Via, Civico) values ('WOEFYC08T48X719U', 'Bard', 'Plowes', 'Meccanico', 'Vietnam', 'Cam Lâm', 'Sauthoff', '50722');
insert into Dipendente (CF, Nome, Cognome, Mansione, Nazione, Città, Via, Civico) values ('MSJGWX71L84N631E', 'Gusty', 'Geere', 'Dirigente', 'Zambia', 'Mpika', 'Hanson', '7143');
insert into Dipendente (CF, Nome, Cognome, Mansione, Nazione, Città, Via, Civico) values ('AFMKQX72L33P459Z', 'Genvieve', 'Sidney', 'Meccanico', 'Indonesia', 'Masu', 'Holy Cross', '702');
insert into Dipendente (CF, Nome, Cognome, Mansione, Nazione, Città, Via, Civico) values ('JTNWBA40Q91M944E', 'Dmitri', 'Cantrell', 'Impiegato', 'Indonesia', 'Biris Daja', 'Warner', '8');
insert into Dipendente (CF, Nome, Cognome, Mansione, Nazione, Città, Via, Civico) values ('BLUCKA20B66A861Y', 'Luke', 'Benardet', 'Meccanico', 'China', 'Xiayang', 'Bonner', '8274');
insert into Dipendente (CF, Nome, Cognome, Mansione, Nazione, Città, Via, Civico) values ('OAGPUY33B64B096J', 'Web', 'Bottoner', 'Impiegato', 'China', 'Jiawu', 'Lakeland', '98724');
insert into Dipendente (CF, Nome, Cognome, Mansione, Nazione, Città, Via, Civico) values ('DUJRNT88M89Q100V', 'Shaun', 'Stivens', 'Dirigente', 'Nigeria', 'Gembu', 'Garrison', '0');
insert into Dipendente (CF, Nome, Cognome, Mansione, Nazione, Città, Via, Civico) values ('LKEHQC72Z31H581O', 'Gabriel', 'Bake', 'Meccanico', 'Philippines', 'Banag', 'Parkside', '315');
insert into Dipendente (CF, Nome, Cognome, Mansione, Nazione, Città, Via, Civico) values ('CMQXWH47E24N990P', 'Craig', 'Cathro', 'Dirigente', 'Nepal', 'Dipayal', 'Burrows', '4535');
insert into Dipendente (CF, Nome, Cognome, Mansione, Nazione, Città, Via, Civico) values ('TJLVZI31W89M512D', 'North', 'Petriello', 'Impiegato', 'Russia', 'Sarmanovo', 'Fieldstone', '5713');
