insert into Modello (Nome, Costruttore, Inizio_produzione) values ('Continental GT', 'Bentley', 2007);
insert into Modello (Nome, Costruttore, Inizio_produzione) values ('tC', 'Scion', 2005);
insert into Modello (Nome, Costruttore, Inizio_produzione) values ('MDX', 'Acura', 2001);
insert into Modello (Nome, Costruttore, Inizio_produzione) values ('Allroad', 'Audi', 2004);
insert into Modello (Nome, Costruttore, Inizio_produzione) values ('Prius', 'Toyota', 2001);
insert into Modello (Nome, Costruttore, Inizio_produzione) values ('CX', 'Citroën', 1989);
insert into Modello (Nome, Costruttore, Inizio_produzione) values ('Element', 'Honda', 2009);
insert into Modello (Nome, Costruttore, Inizio_produzione) values ('Impreza', 'Subaru', 2002);
insert into Modello (Nome, Costruttore, Inizio_produzione) values ('Dakota Club', 'Dodge', 2006);
insert into Modello (Nome, Costruttore, Inizio_produzione) values ('S-Series', 'Saturn', 1997);
insert into Modello (Nome, Costruttore, Inizio_produzione) values ('Altima', 'Nissan', 1993);
insert into Modello (Nome, Costruttore, Inizio_produzione) values ('Rabbit', 'Volkswagen', 2010);
insert into Modello (Nome, Costruttore, Inizio_produzione) values ('Mini Cooper', 'Austin', 1964);
insert into Modello (Nome, Costruttore, Inizio_produzione) values ('Mazda3', 'Mazda', 2006);
insert into Modello (Nome, Costruttore, Inizio_produzione) values ('Sedona', 'Kia', 2006);
insert into Modello (Nome, Costruttore, Inizio_produzione) values ('Challenger', 'Mitsubishi', 2002);
insert into Modello (Nome, Costruttore, Inizio_produzione) values ('Camry', 'Toyota', 2010);
insert into Modello (Nome, Costruttore, Inizio_produzione) values ('Q7', 'Audi', 2011);
insert into Modello (Nome, Costruttore, Inizio_produzione) values ('2500', 'Chevrolet', 2000);
insert into Modello (Nome, Costruttore, Inizio_produzione) values ('62', 'Maybach', 2008);
insert into Modello (Nome, Costruttore, Inizio_produzione) values ('Ramcharger', 'Dodge', 1992);
insert into Modello (Nome, Costruttore, Inizio_produzione) values ('ZX2', 'Ford', 2002);
insert into Modello (Nome, Costruttore, Inizio_produzione) values ('Electra', 'Buick', 1990);
insert into Modello (Nome, Costruttore, Inizio_produzione) values ('Hemisfear', 'Foose', 2007);
insert into Modello (Nome, Costruttore, Inizio_produzione) values ('S10', 'Chevrolet', 1995);
