insert into Optional (Codice, Categoria, Fornitore) values ('JLNUDFYSOQVAGCB', 'Head-up Display', 'GMC');
insert into Optional (Codice, Categoria, Fornitore) values ('NRGAKTLIOXWEJPF', 'Head-up Display', 'Cadillac');
insert into Optional (Codice, Categoria, Fornitore) values ('FDNIREQGHXUMTVO', 'Telecamera 360', 'Volkswagen');
insert into Optional (Codice, Categoria, Fornitore) values ('MZEYUWVBTRKJIPS', 'Head-up Display', 'Hyundai');
insert into Optional (Codice, Categoria, Fornitore) values ('VDQGZXCFELWOJYS', 'Telecamera 360', 'Pontiac');
insert into Optional (Codice, Categoria, Fornitore) values ('GPTSAJKVXQIMELD', 'Head-up Display', 'Volvo');
insert into Optional (Codice, Categoria, Fornitore) values ('EGSRMAKJPIDWXZU', 'Telecamera 360', 'Volkswagen');
insert into Optional (Codice, Categoria, Fornitore) values ('NYZQPBJCDFTIKHG', 'Head-up Display', 'Bentley');
insert into Optional (Codice, Categoria, Fornitore) values ('VZRCBYQLKEJHAIN', 'Telecamera 360', 'Mitsubishi');
insert into Optional (Codice, Categoria, Fornitore) values ('PRKICFTJGUQMEAY', 'Head-up Display', 'Chevrolet');
insert into Optional (Codice, Categoria, Fornitore) values ('BNLDAMEVOXQFSIT', 'Mantenimento corsia', 'Dodge');
insert into Optional (Codice, Categoria, Fornitore) values ('KXQVAFMERTGYUDJ', 'Telecamera 360', 'Volkswagen');
insert into Optional (Codice, Categoria, Fornitore) values ('PBZHMJXWEGCNLSR', 'Telecamera 360', 'Buick');
insert into Optional (Codice, Categoria, Fornitore) values ('UKDIRLJBWQTNMYO', 'Guida Autonoma', 'Infiniti');
insert into Optional (Codice, Categoria, Fornitore) values ('GCDLBHYQVZJTRPF', 'Mantenimento corsia', 'Jeep');
insert into Optional (Codice, Categoria, Fornitore) values ('QWAJFVDOKUNBIZE', 'Telecamera 360', 'Mitsubishi');
insert into Optional (Codice, Categoria, Fornitore) values ('LIPMSONHXJWEDGT', 'Cruise Controll Adattivo', 'Nissan');
insert into Optional (Codice, Categoria, Fornitore) values ('JAKLBSXDZEUPVOF', 'Head-up Display', 'Mazda');
insert into Optional (Codice, Categoria, Fornitore) values ('ALVZIRWCJOTGKDU', 'Telecamera 360', 'Isuzu');
insert into Optional (Codice, Categoria, Fornitore) values ('ZXJCGUQKDPWOSNE', 'Telecamera 360', 'Ford');
insert into Optional (Codice, Categoria, Fornitore) values ('GTBEKCRVIUMLOSF', 'Cruise Controll Adattivo', 'Pontiac');
insert into Optional (Codice, Categoria, Fornitore) values ('BDHTFKAZWYMVRLS', 'Head-up Display', 'Daewoo');
insert into Optional (Codice, Categoria, Fornitore) values ('LEHBYAUXSTRZGOI', 'Head-up Display', 'Nissan');
insert into Optional (Codice, Categoria, Fornitore) values ('QVIGBHFNSRJTKDA', 'Telecamera 360', 'Toyota');
insert into Optional (Codice, Categoria, Fornitore) values ('XDLMQPECIOFJTGA', 'Telecamera 360', 'Ford');
insert into Optional (Codice, Categoria, Fornitore) values ('DWGLOQNHYACVJBX', 'Telecamera 360', 'Chevrolet');
insert into Optional (Codice, Categoria, Fornitore) values ('KAEPDTXVHRZJGOC', 'Head-up Display', 'Saab');
insert into Optional (Codice, Categoria, Fornitore) values ('UXZCLMKPFHRYQVI', 'Telecamera 360', 'Pontiac');
insert into Optional (Codice, Categoria, Fornitore) values ('IANVGWOJUKLCREP', 'Head-up Display', 'Mitsubishi');
insert into Optional (Codice, Categoria, Fornitore) values ('VXZYLSCGEQPURJH', 'Cruise Controll Adattivo', 'Pontiac');
insert into Optional (Codice, Categoria, Fornitore) values ('RHMOKWNVLAZJSIU', 'Telecamera 360', 'Toyota');
insert into Optional (Codice, Categoria, Fornitore) values ('LVFIBSGPJRTUHWD', 'Head-up Display', 'Chevrolet');
insert into Optional (Codice, Categoria, Fornitore) values ('ULMVWEIOCPRDKTH', 'Cruise Controll Adattivo', 'Land Rover');
insert into Optional (Codice, Categoria, Fornitore) values ('YOPUWHISJCEXLVQ', 'Telecamera 360', 'Dodge');
insert into Optional (Codice, Categoria, Fornitore) values ('VFEGMDQYZTRWBSL', 'Head-up Display', 'Nissan');
insert into Optional (Codice, Categoria, Fornitore) values ('CDNGTFRMSLAZBQE', 'Guida Autonoma', 'Hyundai');
insert into Optional (Codice, Categoria, Fornitore) values ('YNTWSEVLFROXAGD', 'Telecamera 360', 'Fillmore');
insert into Optional (Codice, Categoria, Fornitore) values ('PDZOXTCYUVNKHSF', 'Telecamera 360', 'Dodge');
insert into Optional (Codice, Categoria, Fornitore) values ('HFQPVJCATZBWYDX', 'Telecamera 360', 'Nissan');
insert into Optional (Codice, Categoria, Fornitore) values ('WYUCONSRVGTXDJK', 'Guida Autonoma', 'Pontiac');
insert into Optional (Codice, Categoria, Fornitore) values ('SLDEPIHZWTXOJVM', 'Telecamera 360', 'Infiniti');
insert into Optional (Codice, Categoria, Fornitore) values ('VTFSQHRKUMBOXAC', 'Guida Autonoma', 'Mazda');
insert into Optional (Codice, Categoria, Fornitore) values ('TQXSNMDVRBFKPAE', 'Head-up Display', 'Ford');
insert into Optional (Codice, Categoria, Fornitore) values ('LTVBKANXDYIQECU', 'Telecamera 360', 'Mercedes-Benz');
insert into Optional (Codice, Categoria, Fornitore) values ('CZEMYLSTOQIHWUP', 'Cruise Controll Adattivo', 'Acura');
insert into Optional (Codice, Categoria, Fornitore) values ('TVXYUSQNMPERLBH', 'Telecamera 360', 'Mercedes-Benz');
insert into Optional (Codice, Categoria, Fornitore) values ('IZDCPTXSAMFJBYE', 'Telecamera 360', 'Jeep');
insert into Optional (Codice, Categoria, Fornitore) values ('NQYEWHCPDSRLXMK', 'Head-up Display', 'Jeep');
insert into Optional (Codice, Categoria, Fornitore) values ('UOIAZMELSDVXJCP', 'Telecamera 360', 'Nissan');
insert into Optional (Codice, Categoria, Fornitore) values ('RBACHGKVTZFEWJQ', 'Telecamera 360', 'Chevrolet');
