insert into Sede (Id, Tipo, Numero, Email, Nazione, Città, Via, Civico) values (1, 'Concessionario', '7550543635', 'eridsdell0@yolasite.com', 'Haiti', 'Dondon', '82070 Boyd Street', '4');
insert into Sede (Id, Tipo, Numero, Email, Nazione, Città, Via, Civico) values (2, 'Officina', '7430400086', 'jberry1@slate.com', 'United States', 'Springfield', '76 Heath Parkway', '6404');
insert into Sede (Id, Tipo, Numero, Email, Nazione, Città, Via, Civico) values (3, 'Concessionario', '9015282982', 'ptoomer2@phoca.cz', 'Philippines', 'Tudela', '97 Surrey Street', '1246');
insert into Sede (Id, Tipo, Numero, Email, Nazione, Città, Via, Civico) values (4, 'Concessionario', '9017668137', 'mmuffitt3@hhs.gov', 'Ukraine', 'Lopatyn', '5521 Victoria Pass', '1');
insert into Sede (Id, Tipo, Numero, Email, Nazione, Città, Via, Civico) values (5, 'Officina', '9705325602', 'gduell4@sina.com.cn', 'Botswana', 'Francistown', '995 Algoma Point', '39');
insert into Sede (Id, Tipo, Numero, Email, Nazione, Città, Via, Civico) values (6, 'Officina', '3160864161', 'zwakelam5@is.gd', 'Philippines', 'Tocok', '8 Holy Cross Point', '9535');
insert into Sede (Id, Tipo, Numero, Email, Nazione, Città, Via, Civico) values (7, 'Concessionario', '8546698406', 'sgringley6@wunderground.com', 'France', 'Oullins', '9 Arrowood Terrace', '19074');
insert into Sede (Id, Tipo, Numero, Email, Nazione, Città, Via, Civico) values (8, 'Officina', '4405881706', 'erist7@chron.com', 'Albania', 'Mollas', '670 Rowland Parkway', '76123');
insert into Sede (Id, Tipo, Numero, Email, Nazione, Città, Via, Civico) values (9, 'Officina', '2785294432', 'mbockmaster8@jigsy.com', 'Egypt', 'Luxor', '6941 Goodland Court', '8');
insert into Sede (Id, Tipo, Numero, Email, Nazione, Città, Via, Civico) values (10, 'Officina', '4969164605', 'alinham9@godaddy.com', 'Syria', 'Muḩambal', '4 Maryland Plaza', '10');
insert into Sede (Id, Tipo, Numero, Email, Nazione, Città, Via, Civico) values (11, 'Concessionario', '9014769194', 'ejefferysa@bbb.org', 'Brazil', 'Barão de Melgaço', '051 Raven Street', '94');
insert into Sede (Id, Tipo, Numero, Email, Nazione, Città, Via, Civico) values (12, 'Officina', '9124370460', 'kfeaviourb@dmoz.org', 'Philippines', 'Bagong Barrio', '34 Harper Hill', '47009');
insert into Sede (Id, Tipo, Numero, Email, Nazione, Città, Via, Civico) values (13, 'Officina', '7933731704', 'wovenc@google.com', 'China', 'Lishu', '38915 1st Trail', '5');
insert into Sede (Id, Tipo, Numero, Email, Nazione, Città, Via, Civico) values (14, 'Officina', '1823169887', 'kwrightond@furl.net', 'Russia', 'Tunoshna', '58816 Blaine Drive', '5');
insert into Sede (Id, Tipo, Numero, Email, Nazione, Città, Via, Civico) values (15, 'Officina', '6118796520', 'hcollyere@nydailynews.com', 'Indonesia', 'Lurut', '18 Miller Alley', '289');
insert into Sede (Id, Tipo, Numero, Email, Nazione, Città, Via, Civico) values (16, 'Concessionario', '3158499360', 'earrandalef@biglobe.ne.jp', 'Philippines', 'Haguimit', '5 Carey Junction', '0009');
insert into Sede (Id, Tipo, Numero, Email, Nazione, Città, Via, Civico) values (17, 'Officina', '5690643650', 'swaythingg@state.tx.us', 'China', 'Hepingyizu', '27 Veith Trail', '584');
insert into Sede (Id, Tipo, Numero, Email, Nazione, Città, Via, Civico) values (18, 'Officina', '6046744268', 'ianderh@twitter.com', 'China', 'Daqiao', '1516 Armistice Center', '6187');
insert into Sede (Id, Tipo, Numero, Email, Nazione, Città, Via, Civico) values (19, 'Concessionario', '3610413088', 'rromaninii@washingtonpost.com', 'Sweden', 'Sjöbo', '3 Badeau Terrace', '573');
insert into Sede (Id, Tipo, Numero, Email, Nazione, Città, Via, Civico) values (20, 'Concessionario', '0889069139', 'rbridgwoodj@apache.org', 'China', 'Huanghuai', '399 Gulseth Drive', '2');
insert into Sede (Id, Tipo, Numero, Email, Nazione, Città, Via, Civico) values (21, 'Officina', '2270122392', 'lwhitemank@nydailynews.com', 'Egypt', 'Samannūd', '0 Jenifer Alley', '8');
insert into Sede (Id, Tipo, Numero, Email, Nazione, Città, Via, Civico) values (22, 'Officina', '4371384278', 'sfillinghaml@yahoo.co.jp', 'North Korea', 'Kosan', '0918 Elgar Avenue', '66240');
insert into Sede (Id, Tipo, Numero, Email, Nazione, Città, Via, Civico) values (23, 'Officina', '0886329107', 'dhutcheonm@cbsnews.com', 'China', 'Nankun', '38144 Golden Leaf Trail', '7');
insert into Sede (Id, Tipo, Numero, Email, Nazione, Città, Via, Civico) values (24, 'Officina', '7850378889', 'lringn@stanford.edu', 'Brazil', 'Quatá', '597 Mayfield Place', '014');
insert into Sede (Id, Tipo, Numero, Email, Nazione, Città, Via, Civico) values (25, 'Concessionario', '7718352586', 'ddemitrio@ezinearticles.com', 'Brazil', 'Brotas', '88554 Straubel Pass', '34680');
insert into Sede (Id, Tipo, Numero, Email, Nazione, Città, Via, Civico) values (26, 'Concessionario', '5464879567', 'pferribyp@last.fm', 'Colombia', 'Zipaquirá', '902 Luster Way', '06');
insert into Sede (Id, Tipo, Numero, Email, Nazione, Città, Via, Civico) values (27, 'Concessionario', '3356358599', 'cyansonq@ucla.edu', 'Greece', 'Loúros', '695 Holy Cross Junction', '1736');
insert into Sede (Id, Tipo, Numero, Email, Nazione, Città, Via, Civico) values (28, 'Officina', '0437393240', 'dellereyr@oaic.gov.au', 'Nigeria', 'Zalanga', '10746 Reinke Parkway', '2783');
insert into Sede (Id, Tipo, Numero, Email, Nazione, Città, Via, Civico) values (29, 'Officina', '2531659608', 'ghousons@fastcompany.com', 'Ukraine', 'Marshintsy', '1 Bonner Court', '6627');
insert into Sede (Id, Tipo, Numero, Email, Nazione, Città, Via, Civico) values (30, 'Officina', '2863677473', 'amattockt@blogger.com', 'China', 'Huaqiu', '6347 Trailsway Road', '6599');
insert into Sede (Id, Tipo, Numero, Email, Nazione, Città, Via, Civico) values (31, 'Officina', '9041671252', 'hwilsoneu@so-net.ne.jp', 'Indonesia', 'Ngluwuk', '3594 Memorial Center', '86694');
insert into Sede (Id, Tipo, Numero, Email, Nazione, Città, Via, Civico) values (32, 'Officina', '6056376492', 'kreesev@businessweek.com', 'Kyrgyzstan', 'Kara Suu', '96 Bashford Park', '5');
insert into Sede (Id, Tipo, Numero, Email, Nazione, Città, Via, Civico) values (33, 'Concessionario', '8459657833', 'ccolterw@google.com.au', 'Sudan', 'El Fasher', '693 Farmco Plaza', '9069');
insert into Sede (Id, Tipo, Numero, Email, Nazione, Città, Via, Civico) values (34, 'Officina', '6468642054', 'spouckx@blinklist.com', 'China', 'Yangkang', '00 Stephen Trail', '1');
insert into Sede (Id, Tipo, Numero, Email, Nazione, Città, Via, Civico) values (35, 'Officina', '3639229172', 'sizkoveskiy@bing.com', 'Japan', 'Kan’onjichō', '093 Sheridan Terrace', '687');
insert into Sede (Id, Tipo, Numero, Email, Nazione, Città, Via, Civico) values (36, 'Concessionario', '8451490287', 'ckennefickz@ucoz.com', 'Indonesia', 'Pagarbatu', '43278 Novick Center', '36');
insert into Sede (Id, Tipo, Numero, Email, Nazione, Città, Via, Civico) values (37, 'Officina', '8403716668', 'mdensumbe10@noaa.gov', 'Indonesia', 'Sepulu', '3082 Sycamore Hill', '8136');
insert into Sede (Id, Tipo, Numero, Email, Nazione, Città, Via, Civico) values (38, 'Officina', '8659548439', 'estanes11@constantcontact.com', 'Czech Republic', 'Krásná Hora nad Vltavou', '63525 Darwin Point', '3656');
insert into Sede (Id, Tipo, Numero, Email, Nazione, Città, Via, Civico) values (39, 'Officina', '7641148059', 'abrosini12@cam.ac.uk', 'Indonesia', 'Cimanglid', '76698 Clemons Lane', '32741');
insert into Sede (Id, Tipo, Numero, Email, Nazione, Città, Via, Civico) values (40, 'Officina', '3357931558', 'jbragge13@netscape.com', 'Philippines', 'Malabang', '59 Ridgeview Circle', '750');
insert into Sede (Id, Tipo, Numero, Email, Nazione, Città, Via, Civico) values (41, 'Concessionario', '8228232871', 'gjuppe14@furl.net', 'Nepal', 'Bīrganj', '92 Mosinee Drive', '13905');
insert into Sede (Id, Tipo, Numero, Email, Nazione, Città, Via, Civico) values (42, 'Concessionario', '0089282231', 'ahugonet15@netscape.com', 'France', 'Ploemeur', '80714 Sullivan Court', '8923');
insert into Sede (Id, Tipo, Numero, Email, Nazione, Città, Via, Civico) values (43, 'Officina', '9743734343', 'fjerzykiewicz16@github.com', 'Brazil', 'Ouricuri', '225 Alpine Terrace', '76964');
insert into Sede (Id, Tipo, Numero, Email, Nazione, Città, Via, Civico) values (44, 'Officina', '4434218110', 'ideavin17@senate.gov', 'Poland', 'Kowale Oleckie', '00035 Mockingbird Point', '6741');
insert into Sede (Id, Tipo, Numero, Email, Nazione, Città, Via, Civico) values (45, 'Officina', '3712148778', 'pgarrould18@imgur.com', 'Poland', 'Rudna', '1748 Waxwing Junction', '7');
insert into Sede (Id, Tipo, Numero, Email, Nazione, Città, Via, Civico) values (46, 'Officina', '9258613374', 'kcrow19@va.gov', 'Indonesia', 'Jalgung', '64 Myrtle Drive', '6684');
insert into Sede (Id, Tipo, Numero, Email, Nazione, Città, Via, Civico) values (47, 'Officina', '4727118654', 'nfermoy1a@nba.com', 'Indonesia', 'Anjirserapat', '46 Fuller Plaza', '850');
insert into Sede (Id, Tipo, Numero, Email, Nazione, Città, Via, Civico) values (48, 'Concessionario', '6972927304', 'mraff1b@tuttocitta.it', 'Germany', 'Mülheim an der Ruhr', '5980 Swallow Alley', '74');
insert into Sede (Id, Tipo, Numero, Email, Nazione, Città, Via, Civico) values (49, 'Officina', '7541734629', 'mbrehault1c@jiathis.com', 'Thailand', 'Lam Plai Mat', '3802 Columbus Hill', '1');
insert into Sede (Id, Tipo, Numero, Email, Nazione, Città, Via, Civico) values (50, 'Concessionario', '2304237545', 'peary1d@list-manage.com', 'Albania', 'Krutja e Poshtme', '28932 Riverside Trail', '901');
