insert into Sede (ID, Tipo, Nazione, Città, Via, Civico) values (1, 'Concessionario', 'Tanzania', 'Makungu', '4 Grayhawk Point', '3617');
insert into Sede (ID, Tipo, Nazione, Città, Via, Civico) values (2, 'Officina', 'Poland', 'Rakszawa', '8076 East Center', '0');
insert into Sede (ID, Tipo, Nazione, Città, Via, Civico) values (3, 'Concessionario', 'Poland', 'Parzęczew', '04650 Southridge Drive', '4773');
insert into Sede (ID, Tipo, Nazione, Città, Via, Civico) values (4, 'Concessionario', 'Indonesia', 'Pili', '1 Chinook Pass', '44');
insert into Sede (ID, Tipo, Nazione, Città, Via, Civico) values (5, 'Officina', 'Russia', 'Krasnyye Chetai', '6750 Northfield Crossing', '278');
insert into Sede (ID, Tipo, Nazione, Città, Via, Civico) values (6, 'Officina', 'Philippines', 'Alangilanan', '48 Melvin Circle', '5');
insert into Sede (ID, Tipo, Nazione, Città, Via, Civico) values (7, 'Concessionario', 'China', 'Yushan', '36 Transport Park', '58');
insert into Sede (ID, Tipo, Nazione, Città, Via, Civico) values (8, 'Officina', 'China', 'Yangzhuang', '9348 Little Fleur Point', '11660');
insert into Sede (ID, Tipo, Nazione, Città, Via, Civico) values (9, 'Officina', 'Japan', 'Tomiya', '04165 Straubel Place', '579');
insert into Sede (ID, Tipo, Nazione, Città, Via, Civico) values (10, 'Officina', 'Thailand', 'Det Udom', '848 Jenifer Terrace', '558');
insert into Sede (ID, Tipo, Nazione, Città, Via, Civico) values (11, 'Concessionario', 'Indonesia', 'Sijunjung', '5 Bluejay Alley', '3');
insert into Sede (ID, Tipo, Nazione, Città, Via, Civico) values (12, 'Officina', 'Russia', 'Bizhbulyak', '9 Village Way', '088');
insert into Sede (ID, Tipo, Nazione, Città, Via, Civico) values (13, 'Officina', 'Brazil', 'Solânea', '9 Barnett Court', '0514');
insert into Sede (ID, Tipo, Nazione, Città, Via, Civico) values (14, 'Officina', 'China', 'Jingling', '8 Milwaukee Plaza', '536');
insert into Sede (ID, Tipo, Nazione, Città, Via, Civico) values (15, 'Officina', 'China', 'Dancheng', '5360 Kinsman Place', '6906');
insert into Sede (ID, Tipo, Nazione, Città, Via, Civico) values (16, 'Concessionario', 'Dominican Republic', 'Bánica', '1822 American Ash Court', '059');
insert into Sede (ID, Tipo, Nazione, Città, Via, Civico) values (17, 'Officina', 'Madagascar', 'Toliara', '922 Cambridge Point', '7179');
insert into Sede (ID, Tipo, Nazione, Città, Via, Civico) values (18, 'Officina', 'Greece', 'Stefanavíkion', '34279 Autumn Leaf Parkway', '606');
insert into Sede (ID, Tipo, Nazione, Città, Via, Civico) values (19, 'Concessionario', 'Malaysia', 'Butterworth', '3364 Shopko Place', '82264');
insert into Sede (ID, Tipo, Nazione, Città, Via, Civico) values (20, 'Concessionario', 'Poland', 'Pruchnik', '008 Butternut Way', '593');
insert into Sede (ID, Tipo, Nazione, Città, Via, Civico) values (21, 'Officina', 'Netherlands', 'Katwijk', '28 Delaware Hill', '4073');
insert into Sede (ID, Tipo, Nazione, Città, Via, Civico) values (22, 'Officina', 'Indonesia', 'Sinjai', '12 Independence Way', '033');
insert into Sede (ID, Tipo, Nazione, Città, Via, Civico) values (23, 'Officina', 'Serbia', 'Stepojevac', '8 Northridge Terrace', '6');
insert into Sede (ID, Tipo, Nazione, Città, Via, Civico) values (24, 'Officina', 'China', 'Basar', '96501 Rieder Trail', '0');
insert into Sede (ID, Tipo, Nazione, Città, Via, Civico) values (25, 'Concessionario', 'France', 'Troyes', '60512 Anzinger Place', '70');
insert into Sede (ID, Tipo, Nazione, Città, Via, Civico) values (26, 'Concessionario', 'Poland', 'Nowy Staw', '70 Manufacturers Place', '526');
insert into Sede (ID, Tipo, Nazione, Città, Via, Civico) values (27, 'Concessionario', 'Poland', 'Dzików Stary', '52 Texas Point', '1932');
insert into Sede (ID, Tipo, Nazione, Città, Via, Civico) values (28, 'Officina', 'Russia', 'Priyutovo', '0 Brentwood Pass', '92166');
insert into Sede (ID, Tipo, Nazione, Città, Via, Civico) values (29, 'Officina', 'Luxembourg', 'Sandweiler', '5795 6th Alley', '1644');
insert into Sede (ID, Tipo, Nazione, Città, Via, Civico) values (30, 'Officina', 'Indonesia', 'Cilongkrangpusaka', '1557 Atwood Drive', '21');
insert into Sede (ID, Tipo, Nazione, Città, Via, Civico) values (31, 'Officina', 'Philippines', 'Tiwi', '108 Del Sol Way', '14');
insert into Sede (ID, Tipo, Nazione, Città, Via, Civico) values (32, 'Officina', 'North Korea', 'Kapsan-ŭp', '2 Lawn Avenue', '04331');
insert into Sede (ID, Tipo, Nazione, Città, Via, Civico) values (33, 'Concessionario', 'Brazil', 'São Bento', '9075 Homewood Plaza', '0674');
insert into Sede (ID, Tipo, Nazione, Città, Via, Civico) values (34, 'Officina', 'Marshall Islands', 'Enewetak', '146 Nancy Pass', '066');
insert into Sede (ID, Tipo, Nazione, Città, Via, Civico) values (35, 'Officina', 'Indonesia', 'Kebonan', '1702 Talisman Crossing', '3');
insert into Sede (ID, Tipo, Nazione, Città, Via, Civico) values (36, 'Concessionario', 'Croatia', 'Bibinje', '29114 Eastwood Way', '7');
insert into Sede (ID, Tipo, Nazione, Città, Via, Civico) values (37, 'Officina', 'Brazil', 'Barra do Bugres', '28 Hoepker Park', '9');
insert into Sede (ID, Tipo, Nazione, Città, Via, Civico) values (38, 'Officina', 'Afghanistan', 'Khānaqāh', '97676 Cascade Trail', '68');
insert into Sede (ID, Tipo, Nazione, Città, Via, Civico) values (39, 'Officina', 'China', 'Macheng', '2934 Rockefeller Way', '10161');
insert into Sede (ID, Tipo, Nazione, Città, Via, Civico) values (40, 'Officina', 'Dominican Republic', 'Villa Bisonó', '38 Shoshone Pass', '098');
insert into Sede (ID, Tipo, Nazione, Città, Via, Civico) values (41, 'Concessionario', 'Vietnam', 'Thị Trấn Việt Quang', '1 Sunbrook Place', '609');
insert into Sede (ID, Tipo, Nazione, Città, Via, Civico) values (42, 'Concessionario', 'Poland', 'Murowana Goślina', '798 Manufacturers Trail', '0');
insert into Sede (ID, Tipo, Nazione, Città, Via, Civico) values (43, 'Officina', 'Sweden', 'Tanumshede', '7 Gale Circle', '2');
insert into Sede (ID, Tipo, Nazione, Città, Via, Civico) values (44, 'Officina', 'France', 'Saint-Priest-en-Jarez', '9213 Burning Wood Junction', '1359');
insert into Sede (ID, Tipo, Nazione, Città, Via, Civico) values (45, 'Officina', 'China', 'Hongshunli', '23322 Donald Plaza', '438');
insert into Sede (ID, Tipo, Nazione, Città, Via, Civico) values (46, 'Officina', 'Vietnam', 'Sa Pá', '766 Milwaukee Crossing', '13');
insert into Sede (ID, Tipo, Nazione, Città, Via, Civico) values (47, 'Officina', 'Yemen', 'As Sūq al Jadīd', '2 Rowland Pass', '50');
insert into Sede (ID, Tipo, Nazione, Città, Via, Civico) values (48, 'Concessionario', 'Botswana', 'Mathakola', '0 Lien Park', '45457');
insert into Sede (ID, Tipo, Nazione, Città, Via, Civico) values (49, 'Officina', 'Canada', 'Prince Edward', '715 Emmet Alley', '6613');
insert into Sede (ID, Tipo, Nazione, Città, Via, Civico) values (50, 'Concessionario', 'Poland', 'Zebrzydowice', '77 Northport Court', '48941');
