insert into acquirente (cf, nome, nazione, città, via, civico) values ('ITCQBG87W72Z751R', 'Sarine', 'Cuba', 'Boyeros', 'Schurz', '9');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('BOXCES30J08D424E', 'Fair', 'China', 'Chenqing', 'Lakewood Gardens', '3631');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('ELDMXA79J55Z620X', 'Raynard', 'Russia', 'Ten’gushevo', 'Arkansas', '33057');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('MWRPHQ12Z32R218N', 'Odelle', 'Brazil', 'Mirandopólis', 'Armistice', '58363');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('YAWXOK98G08G995C', 'Belvia', 'Ukraine', 'Shpola', 'Sachtjen', '5');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('YDXCNH33A90P058T', 'Camala', 'Netherlands', 'Kerkrade', 'Kropf', '377');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('WAIFDN79H78G459F', 'Chiquita', 'Indonesia', 'Krajansumbermujur', '1st', '82');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('YCEOUN45G91D747R', 'Scarface', 'Honduras', 'El Lolo', 'Esker', '6964');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('CADTUF83O09N399T', 'Daveta', 'Indonesia', 'Kutamandarakan', 'Acker', '2');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('RTLYMP82H88C213H', 'Marty', 'Honduras', 'Loma Alta', 'Killdeer', '1');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('FWOQSH24N87O443I', 'Kalli', 'Philippines', 'Bula', 'Ohio', '32');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('ALXDQK14U64M453R', 'Andriette', 'Portugal', 'Sarrazola', 'Boyd', '3');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('ZGACSO50E32Q677W', 'Norby', 'France', 'Vichy', 'Evergreen', '6');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('KWGFDS32W08S798U', 'Bear', 'Sweden', 'Vilhelmina', 'Maple', '93087');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('ADCXYW05U15T994W', 'Thomasine', 'Indonesia', 'Tarikolot', 'Sunbrook', '91562');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('GRJWSC21O68L152K', 'Stinky', 'Colombia', 'Puerto Santander', 'Nancy', '2052');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('VFOEAK46M43H493A', 'Chrissy', 'Malaysia', 'Putrajaya', 'Express', '80378');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('KQAGIN08U20E937G', 'Tamas', 'China', 'Leyuan', 'Petterle', '4829');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('MQAHSI53D80I297T', 'Burl', 'Vietnam', 'Thị Trấn Than Uyên', 'Lukken', '8');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('YRWOXQ80X78H901U', 'Laney', 'Brazil', 'Mutum', 'Delladonna', '1904');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('KCPAXF94M32A511J', 'Dorrie', 'Russia', 'Pavlovskaya', 'American Ash', '04526');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('HQOWVY43W81J307R', 'Sharyl', 'France', 'Paris 07', 'Dwight', '6937');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('XFSOEI81Q64C883O', 'Latashia', 'United States', 'Savannah', 'Northland', '192');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('RJQBFZ57G51U660O', 'Kristin', 'Portugal', 'Carrazeda de Ansiães', 'Judy', '03');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('YWIERS98K63G137Z', 'Sula', 'Thailand', 'Samphanthawong', 'Maple Wood', '987');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('YNCVJP86U48N180E', 'Bonnee', 'China', 'Hushan', '7th', '186');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('VYTMIF15M41C073M', 'Wini', 'Philippines', 'Montaneza', 'Shoshone', '61');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('VUJATX64F60Z606C', 'Clare', 'Sudan', 'Bārah', 'Luster', '498');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('SNQXDB81M01M900W', 'Katey', 'Indonesia', 'Potlot', 'Pankratz', '5530');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('JSIOBX73Y69M957Y', 'Reidar', 'Argentina', 'Saladas', 'Arapahoe', '33');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('ROZGAX49M34D859R', 'Wells', 'Albania', 'Pojan', '8th', '127');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('ZWJARH45C29K185N', 'Royce', 'Democratic Republic of the Congo', 'Mushie', 'Park Meadow', '7');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('IGKEMP20F76W603P', 'Ervin', 'Spain', 'Tarragona', 'Twin Pines', '221');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('ISXKVT20W07J948R', 'Kale', 'France', 'Lyon', 'Kipling', '7122');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('GLDZFS18O17Y456F', 'Etienne', 'Poland', 'Stalowa Wola', 'Artisan', '087');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('MGOVXF00E99I837R', 'Lira', 'China', 'Qixing', 'School', '2393');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('OQPNST99Y77F385T', 'Phillipp', 'Indonesia', 'Sopo', 'Algoma', '2');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('MUVSHF19D86Q339X', 'Yolande', 'Brazil', 'Barcarena', 'Birchwood', '8');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('PCNXEU71H01Q073Z', 'Korella', 'Slovenia', 'Tržič', 'Hintze', '12');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('DLPBKF64D36A038Q', 'Kathrine', 'Haiti', 'Chambellan', 'Farwell', '9');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('HQCLVY77W16Y218O', 'Shawn', 'Indonesia', 'Watulabara', 'Talmadge', '1946');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('MWISBF30Z22U164B', 'Denver', 'Vietnam', 'Phủ Thông', 'Pearson', '4');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('CDAVOH01Q77H245U', 'Stearne', 'Pakistan', 'Utmānzai', 'Browning', '7');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('YDLEZV45U40Q831B', 'Berke', 'China', 'Wuyang', 'Shopko', '45960');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('TRWUKF72D56V885O', 'Giustina', 'Serbia', 'Hrtkovci', 'Springview', '63');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('BELPFJ09D32D700L', 'Kittie', 'Vietnam', 'Gò Dầu', 'Hayes', '07');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('KTJIFG56E77I737S', 'Wallie', 'China', 'Huanghe', 'Lerdahl', '2');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('CYQXUG64Y57J699N', 'Alissa', 'China', 'Gantang', 'Fordem', '068');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('FNLIEM34T92R478D', 'Pasquale', 'Russia', 'Imeni Babushkina', 'Lukken', '70760');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('BXNULI81R62L224W', 'Adolphe', 'Philippines', 'Puro Pinget', 'Little Fleur', '5424');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('ZVLBTJ23A98D123Q', 'Lorens', 'Afghanistan', 'Dasht-e Archī', 'Holmberg', '1783');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('YBKILM62H53I163W', 'Lou', 'China', 'Jiangshan', 'Oak', '2');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('JTIXOQ56W81Y069W', 'Cassaundra', 'Mexico', 'Solidaridad', 'Montana', '6879');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('UFZRDX17L70R197A', 'Eunice', 'Indonesia', 'Telangi Satu', 'Mayfield', '2198');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('RNDVUZ82X25Z898L', 'Drona', 'Portugal', 'Portela', 'Elgar', '8');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('FDRUXZ77P92K569U', 'Terri', 'Russia', 'Blagoveshchenka', 'Loftsgordon', '06');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('WXFKHS64M18Y630R', 'Carissa', 'Uruguay', 'Soca', 'Hollow Ridge', '19');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('NRYOZH46D67K096I', 'Amby', 'Peru', 'Chalcos', 'Hazelcrest', '02');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('LRZFXM74E23Q063E', 'Emmaline', 'China', 'Laiguangying', 'Homewood', '107');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('UOXCQR34M95H037R', 'Sidnee', 'China', 'Hangzhou', 'Butternut', '1');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('VHEBLQ64T49I653Z', 'Pippo', 'Uganda', 'Nakasongola', 'Columbus', '53');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('LKMFAO73G64J409L', 'Tommy', 'Russia', 'Navashino', 'Sutherland', '07611');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('QFTMRL09X80I369M', 'Daryl', 'Russia', 'Rasskazovo', 'Hayes', '77434');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('LWGCAJ20W04Z164N', 'Ali', 'Indonesia', 'Wonorejo', 'Loomis', '7');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('MSEDIY94H69B507D', 'Cindie', 'China', 'Miao’ertan', 'Debra', '410');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('WEXIOJ79N99I743G', 'Moses', 'Czech Republic', 'Žebrák', 'Lerdahl', '4925');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('FUBHXG78I70G131J', 'Lisle', 'Thailand', 'Khao Khitchakut', 'Grayhawk', '6154');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('ECBKPT24I84O488Y', 'Kelvin', 'France', 'Charenton-le-Pont', 'Hansons', '1472');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('JSCAPO92O73O697N', 'Garwin', 'Nepal', 'Rājbirāj', 'Elka', '535');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('AMSTDI85E60Z568L', 'Lisabeth', 'Central African Republic', 'Berbérati', 'Arizona', '5817');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('BWYZDN34M99U646E', 'Jori', 'Canada', 'Agassiz', 'Karstens', '3');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('UFGXCA25Y56O466M', 'Wesley', 'Mexico', 'El Calvario', 'Ilene', '27');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('NZVODA04T58C855J', 'Juan', 'United States', 'Atlanta', 'Mesta', '50');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('GROVDX04C22D364U', 'Rivalee', 'France', 'Rueil-Malmaison', 'Mandrake', '2121');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('RCHLSZ91T14W946K', 'Bailie', 'Ivory Coast', 'Agnibilékrou', 'Kedzie', '9511');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('DWGAEX17U88S032U', 'Tabina', 'China', 'Hexi', 'Scofield', '42221');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('SFGWLR76V35X986V', 'Brynn', 'Vietnam', 'Yên Lạc', 'Service', '0');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('TEQSKL66L42T170D', 'Orsa', 'China', 'Hengshi', 'Pleasure', '795');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('UMCVDE79H31O171W', 'Rosella', 'Egypt', 'Al Maḩallah al Kubrá', 'Birchwood', '3751');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('FDCEQG14H56A447B', 'Pen', 'Sierra Leone', 'Lunsar', 'Northfield', '90');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('VKSEJI87V60C972B', 'Adams', 'Russia', 'Sorokino', 'Loftsgordon', '9');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('SLFDVQ85F27N248Q', 'Corrie', 'Philippines', 'Surup', 'Scott', '86');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('XGSLID65H55V963Z', 'Merlina', 'Indonesia', 'Lewograran', 'Kensington', '646');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('ELPQUJ54W91H547T', 'Belva', 'Indonesia', 'Amparita', 'Vera', '047');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('MGHTPC98R91K327J', 'Ben', 'Indonesia', 'Mungging', 'Thompson', '6672');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('GFEJPS55T23C050K', 'Collie', 'Portugal', 'Boavista', 'Bluestem', '65842');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('SOYIHR07Q73N200U', 'Vito', 'Bolivia', 'Samaipata', 'Namekagon', '73393');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('WEROGV71P41G646D', 'Jazmin', 'China', 'Huazangsi', 'Memorial', '8');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('DHPCIZ96M22F308A', 'Gilbertine', 'China', 'Taihe', 'Comanche', '2302');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('DSVUJP96O71F774B', 'Steffane', 'Greece', 'Alivéri', 'Roth', '4282');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('KBSRDW04G82G454I', 'Alf', 'Canada', 'Greenwood', 'Beilfuss', '74');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('IMFSLN78I85X209W', 'Dorie', 'Indonesia', 'Utara', 'Glacier Hill', '4');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('ZEATFJ94O38W076C', 'Roland', 'Indonesia', 'Maukaro', 'Moose', '3974');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('EIHKRS26M48G410U', 'Bea', 'Brazil', 'Custódia', 'Becker', '7396');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('SVCHPD90G07D462P', 'Filbert', 'Poland', 'Gierałtowice', 'Bunting', '1189');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('QXVORZ83J45S363J', 'Ruperta', 'Philippines', 'Molave', 'Loomis', '9');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('MXAEYZ81P37D710C', 'Taryn', 'France', 'Ajaccio', 'Homewood', '40921');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('GXVHTZ47R48Q507P', 'Hyacintha', 'South Korea', 'Wanju', 'Anthes', '96832');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('EHCLQO62C22R409V', 'Alma', 'Cuba', 'Santiago de las Vegas', 'Green', '919');
insert into acquirente (cf, nome, nazione, città, via, civico) values ('XQYVOZ52N37R052Z', 'Jany', 'Afghanistan', 'Zīrakī', 'Carioca', '38662');