insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('IRXQTO13C92X230G', 'Shayla', 'Marskell', 'Impiegato', 'China', 'Tuqiao', 'Fairfield', '1');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('ASXRJV53A83W696O', 'Huntley', 'Schleicher', 'Meccanico', 'Argentina', 'Cerrillos', 'Mesta', '2');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('UJQCSH08H86S478V', 'Giuditta', 'Mitton', 'Dirigente', 'Philippines', 'Vitali', 'Pierstorff', '9282');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('AQDOZU86B37F976L', 'Dolf', 'Reilingen', 'Dirigente', 'Bulgaria', 'Brusartsi', 'Ridgeway', '2652');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('TDGSLX81L09Z667E', 'Rubi', 'Hayman', 'Meccanico', 'Brazil', 'Pacatuba', 'Oak', '625');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('JDKMYA33P15H640T', 'Zachery', 'Kolinsky', 'Meccanico', 'Czech Republic', 'Solnice', 'Starling', '02');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('ZKJQXO00L35J645A', 'Grover', 'Sheron', 'Impiegato', 'China', 'Danyang', 'Maywood', '04658');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('EJUXKD58K98G619S', 'Ollie', 'Yetman', 'Dirigente', 'Finland', 'Ylihärmä', 'Tomscot', '1');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('YQOWIS74O43U160K', 'Constantino', 'Jamary', 'Meccanico', 'Brazil', 'Cândido Mota', 'Badeau', '742');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('VIQMCH52M16G692A', 'Winthrop', 'Greenslade', 'Dirigente', 'Netherlands', 'Enschede', 'Graceland', '309');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('FZKVCR20F60T694B', 'Imelda', 'Parcall', 'Meccanico', 'Angola', 'Malanje', 'Swallow', '0181');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('XCTEMO49J94X817A', 'Davis', 'Wison', 'Dirigente', 'Brazil', 'Nova Olímpia', 'Parkside', '88');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('RIBGQE22V54N953P', 'Michail', 'Le Cornu', 'Meccanico', 'Czech Republic', 'Seč', 'Gateway', '95131');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('MHQODF45P80O090O', 'Maxi', 'Gilburt', 'Meccanico', 'China', 'Beiqijia', 'Crownhardt', '0258');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('QYCLAV79E56C026R', 'Cyb', 'McClay', 'Dirigente', 'Chile', 'Llaillay', 'Hazelcrest', '08');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('ZDRVJT03Y38H369V', 'Isabella', 'Beaconsall', 'Meccanico', 'Greece', 'Loutrá', 'Gateway', '22135');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('RNEXHW86G00E322H', 'Joana', 'Francis', 'Dirigente', 'Morocco', 'Mhamid', 'Brickson Park', '45');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('YHJLRT28Q06R652B', 'Eloisa', 'Benbough', 'Impiegato', 'Mauritius', 'Goodlands', 'Alpine', '883');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('SVKPWM54F77T439B', 'Harli', 'Caltun', 'Impiegato', 'Israel', '‘Eilabun', 'Michigan', '1418');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('LNPETB46W93Z249I', 'Sibel', 'Farquarson', 'Dirigente', 'Argentina', 'Charata', 'Reinke', '246');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('FWKHRS28Q83Q713U', 'Wenona', 'MacNeilly', 'Meccanico', 'Brazil', 'Catalão', 'Warner', '433');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('YDAZFS67V30Q125J', 'Rancell', 'Seawell', 'Impiegato', 'China', 'Jiuzhai', 'Orin', '5848');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('ALJYUS61V16F188G', 'Greg', 'Tudbald', 'Meccanico', 'Philippines', 'Leon Postigo', 'Maple Wood', '4592');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('UDMPWZ59T16Q388O', 'Nat', 'Sivell', 'Dirigente', 'China', 'Xixiang', 'Northridge', '9');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('EFSUGZ05K00X037H', 'Sammie', 'Gillebert', 'Dirigente', 'Indonesia', 'Sungai Raya', 'Norway Maple', '1361');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('KJUHZC06T54N618O', 'Beckie', 'Sturman', 'Meccanico', 'Brazil', 'Leopoldina', 'Donald', '5');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('JXSLIO22P65C539R', 'Fredric', 'Wastell', 'Impiegato', 'Ukraine', 'Uzhhorod', 'Sullivan', '8483');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('XJKNZG95J32P847F', 'Christophorus', 'Oertzen', 'Impiegato', 'Nicaragua', 'Jiquilillo', 'Shasta', '8');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('HVNMSU42J99G160Q', 'Trula', 'Priddie', 'Meccanico', 'Sweden', 'Kista', 'Melvin', '48501');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('COXIKB47O40E525S', 'Gay', 'Gilhool', 'Meccanico', 'South Korea', 'Suisan', 'Ludington', '1434');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('AKPUGL37C13T131O', 'Adria', 'Dallinder', 'Impiegato', 'Portugal', 'Vila', 'Green Ridge', '58');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('NGWFER79M19J712G', 'Elfrieda', 'Zorzenoni', 'Meccanico', 'China', 'Lab', 'Summer Ridge', '2');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('PUYNBZ49L98F340K', 'Troy', 'Greenham', 'Impiegato', 'China', 'Qianshan', 'Loomis', '966');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('CVQGMJ21F77D046B', 'Lib', 'Yantsev', 'Meccanico', 'Brazil', 'Ceará Mirim', 'Pennsylvania', '1');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('NOHYKX91B48Z564Z', 'Warner', 'Tulk', 'Meccanico', 'United States', 'Montgomery', 'Manufacturers', '11');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('DNYCOW69X09A062N', 'Stephannie', 'Tire', 'Meccanico', 'Thailand', 'Saba Yoi', 'Dryden', '42146');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('XZTFQD11X27F673U', 'Neely', 'Beddis', 'Impiegato', 'El Salvador', 'Cojutepeque', 'Eastlawn', '84');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('CRUEXO54S16Y214S', 'Guenevere', 'McCaughren', 'Impiegato', 'Poland', 'Tokarnia', 'Browning', '4646');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('HVYNDA91Q15Y214J', 'Yovonnda', 'Chesser', 'Meccanico', 'Poland', 'Nakło nad Notecią', 'Sutherland', '70737');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('ELJSGI10I65L027H', 'Leroi', 'Delmage', 'Meccanico', 'Philippines', 'Sagasa', 'Carey', '6742');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('RKIJTZ66Q91G878R', 'Lorain', 'Leidl', 'Meccanico', 'South Korea', 'Moppo', 'Lunder', '7');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('PDLHUS53Z39X672N', 'Sherill', 'Staggs', 'Dirigente', 'Russia', 'Surovikino', 'Dorton', '065');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('UKGHWE05N55T583H', 'Roze', 'Beaument', 'Dirigente', 'Philippines', 'MacArthur', 'Fairfield', '5');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('TNESHI86S95L399N', 'Ophelia', 'Oscroft', 'Meccanico', 'Finland', 'Muurame', 'West', '2522');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('YGKVDJ50E60S858R', 'Pennie', 'Freezer', 'Meccanico', 'France', 'Blois', 'New Castle', '52');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('BQEXYW27L83D097E', 'Gorden', 'Phalp', 'Dirigente', 'Sweden', 'Solna', 'Blue Bill Park', '0285');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('NJZMXL84P47Y876A', 'Michelina', 'Kielt', 'Meccanico', 'United States', 'Montgomery', 'Delladonna', '60367');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('NFTUKL47N25O255L', 'Cherye', 'Mallord', 'Meccanico', 'Brazil', 'Santa Maria', 'Nobel', '180');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('EGCOVA74U20T230I', 'Hakim', 'Gilbard', 'Meccanico', 'China', 'Delong', 'Washington', '0');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('GVRQOI49B63Y316T', 'Goldi', 'Schwartz', 'Meccanico', 'Russia', 'Shalinskoye', 'Lyons', '95');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('HXFBRK53J72C983A', 'Shalna', 'Sinnett', 'Meccanico', 'China', 'Yantan', 'Eastlawn', '9');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('ISZRGQ56R95R095Y', 'Jaclin', 'Grimble', 'Dirigente', 'Ecuador', 'Machachi', 'Fulton', '4');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('LVWTEQ85S78M359D', 'Appolonia', 'Eakens', 'Meccanico', 'China', 'Yishui', 'Miller', '216');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('HQKINE59X69V180B', 'Ilse', 'Wenban', 'Meccanico', 'Czech Republic', 'Hodkovice nad Mohelkou', 'Eagan', '40');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('OYTBDJ01U89I892I', 'Rebecka', 'Burgiss', 'Dirigente', 'China', 'Changxingbao', 'Northridge', '06077');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('DXIRWF68K75F288P', 'Beverley', 'Cleaton', 'Dirigente', 'Sweden', 'Helsingborg', 'Gateway', '29581');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('AKLEJD17J96V579L', 'Keri', 'Sellen', 'Dirigente', 'Russia', 'Tiksi', 'Thackeray', '94013');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('TUMBLH20X11C429V', 'Griselda', 'Charity', 'Meccanico', 'Armenia', 'Gavarr', 'Orin', '9');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('YHZOIN70P19O081B', 'Zelda', 'Fleay', 'Impiegato', 'Indonesia', 'Pabuaran', 'La Follette', '835');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('ZJCQMU91Q99W061K', 'Ardra', 'Calvert', 'Dirigente', 'Sweden', 'Göteborg', 'Carberry', '31318');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('ZFMLES72U70D691G', 'Dore', 'Dobie', 'Dirigente', 'China', 'Chengmen', 'Cordelia', '73');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('POWCEX33T82V633Z', 'Valle', 'Joseph', 'Impiegato', 'Maldives', 'Muli', 'Dayton', '0790');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('GKIBFD01R73M566O', 'Danit', 'Bromley', 'Impiegato', 'South Africa', 'Hermanus', 'Eliot', '3312');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('CGOEHN77W41S133V', 'Marni', 'Carrigan', 'Dirigente', 'China', 'Golug', 'Clyde Gallagher', '79041');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('DGBZRX29I93E551G', 'Kalinda', 'Davids', 'Impiegato', 'France', 'Rodez', 'Prairieview', '2272');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('KJXTPH71F62L033P', 'Nickolas', 'Taffrey', 'Dirigente', 'Argentina', 'Vera', 'Maple', '39544');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('DYBQIL91R56F694D', 'Salvatore', 'Coleborn', 'Impiegato', 'Indonesia', 'Gunungjulang', 'Service', '83181');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('DVNEKU49J59K492H', 'Basile', 'Sibthorp', 'Dirigente', 'Nicaragua', 'Tola', 'Butternut', '46178');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('DZGVMK38K72L747J', 'Charyl', 'Horick', 'Dirigente', 'China', 'Youchou', 'Commercial', '0');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('WKRBTG02B65V163W', 'Colly', 'Zavattiero', 'Dirigente', 'Indonesia', 'Cantuk Kidul', 'Annamark', '76956');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('KXNWBR99K73C828J', 'Marcelline', 'Janikowski', 'Dirigente', 'Japan', 'Tanushimarumachi-toyoki', 'Manufacturers', '51');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('BDSLOK60Y88M756U', 'Ninnetta', 'Seiler', 'Meccanico', 'United States', 'Charlotte', 'American Ash', '3870');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('TQIBKW13W71U217L', 'Melosa', 'Jost', 'Meccanico', 'China', 'Shangjin', 'Ohio', '3384');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('HFJUDS18E02G934V', 'Johnathan', 'Limon', 'Impiegato', 'Canada', 'Sydney Mines', 'Victoria', '61094');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('QYAUTR98W53O058J', 'Sancho', 'Breitling', 'Impiegato', 'South Korea', 'Yangju', 'Mariners Cove', '69695');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('MEICHA91G72W702S', 'Marijn', 'Donnachie', 'Meccanico', 'Indonesia', 'Bungalaleng', 'Mandrake', '72094');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('NEKMDV48E60T005V', 'Celestyna', 'Alliban', 'Meccanico', 'Indonesia', 'Banjar Sebual', 'Sundown', '34');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('VBHDTI63Q46S693L', 'Juliet', 'Groomebridge', 'Impiegato', 'Nigeria', 'Ilare', 'Talisman', '46396');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('DCXNOS97X42Z482F', 'Gram', 'Ealles', 'Impiegato', 'Serbia', 'Boljevci', 'Kim', '5');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('OZGTBE03O63N831O', 'Mayne', 'Mouse', 'Dirigente', 'France', 'Toulon', 'Helena', '1303');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('JIVCDT90A87B873E', 'Yuma', 'Jiles', 'Impiegato', 'Ecuador', 'Machachi', 'Scofield', '66');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('EVZAPM46K97N776N', 'Jarrett', 'Braisher', 'Meccanico', 'China', 'Gaoyu', 'Shopko', '76926');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('MBQRZX94K84M297Z', 'Bev', 'Bittlestone', 'Dirigente', 'Malaysia', 'Kuala Lumpur', 'Almo', '04375');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('QVNYCL41Y70U752R', 'Morten', 'Seniour', 'Meccanico', 'Ukraine', 'Hupalivka', 'Bartillon', '89');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('MLXDNI17A48Q646G', 'Dianne', 'Stellin', 'Meccanico', 'Philippines', 'Montecillo', 'Old Shore', '8');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('LIZAWO23U38Q596P', 'Hercules', 'Fransoni', 'Dirigente', 'Indonesia', 'Bendosewu', 'Petterle', '737');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('SEUJXO57H67E933A', 'Brig', 'Gouth', 'Dirigente', 'Syria', 'As Sukhnah', 'Hermina', '851');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('NLYWXC14X98U934E', 'Thelma', 'Warrender', 'Dirigente', 'Iceland', 'Borgarnes', 'Stone Corner', '64298');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('KVAGXP81N49P247R', 'Quintus', 'Goodspeed', 'Impiegato', 'Croatia', 'Gospić', 'Emmet', '1301');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('DUGHFS53H53Q357X', 'Laurianne', 'Blaney', 'Meccanico', 'Poland', 'Paradyż', 'Farragut', '6337');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('IHWTGK78I94P938X', 'Costanza', 'Blamires', 'Meccanico', 'Canada', 'Chambly', 'Stuart', '282');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('LPCFRM54Z93K932G', 'Neel', 'Rillett', 'Impiegato', 'Philippines', 'Sugcad', 'Manitowish', '4751');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('UQLEJM66T65B610M', 'Duane', 'Lujan', 'Dirigente', 'Indonesia', 'Emplak', 'Dapin', '8868');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('PQYKLD64B90K274K', 'Auberta', 'McPhillips', 'Meccanico', 'Portugal', 'Fontaínhas', 'Gale', '53561');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('XAFSDE46B55D012Y', 'Yalonda', 'Matteoli', 'Meccanico', 'Poland', 'Miechów Charsznica', 'Charing Cross', '68');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('YVDOPM98P02D243O', 'Thacher', 'Mee', 'Impiegato', 'Portugal', 'Mira', 'Larry', '42');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('GOYSHC91V87Q902K', 'Lanita', 'Skain', 'Meccanico', 'China', 'Dongle', 'Lillian', '2739');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('DNVKAT20M40U622W', 'Bernadene', 'Limrick', 'Dirigente', 'Czech Republic', 'Solnice', 'Logan', '4189');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('XTJGHI68I91I896W', 'Asa', 'Witheford', 'Meccanico', 'China', 'Chenfang', 'Monterey', '96');
insert into dipendente (cf, nome, cognome, mansione, nazione, città, via, civico) values ('HSAGXI69R87X416L', 'Collin', 'Denford', 'Meccanico', 'Syria', 'Aş Şanamayn', 'Stoughton', '288');