insert into modello (nome, costruttore, inizio_produzione) values ('S-Series', 'Saturn', 1999);
insert into modello (nome, costruttore, inizio_produzione) values ('900', 'Saab', 1999);
insert into modello (nome, costruttore, inizio_produzione) values ('GT500', 'Ford', 2008);
insert into modello (nome, costruttore, inizio_produzione) values ('LaCrosse', 'Buick', 2012);
insert into modello (nome, costruttore, inizio_produzione) values ('Montero', 'Mitsubishi', 1993);
insert into modello (nome, costruttore, inizio_produzione) values ('Legacy', 'Subaru', 2007);
insert into modello (nome, costruttore, inizio_produzione) values ('W201', 'Mercedes-Benz', 1990);
insert into modello (nome, costruttore, inizio_produzione) values ('Sorento', 'Kia', 2008);
insert into modello (nome, costruttore, inizio_produzione) values ('2500 Club Coupe', 'GMC', 1998);
insert into modello (nome, costruttore, inizio_produzione) values ('4000s', 'Audi', 1985);
insert into modello (nome, costruttore, inizio_produzione) values ('TT', 'Audi', 2011);
insert into modello (nome, costruttore, inizio_produzione) values ('Loyale', 'Subaru', 1993);
insert into modello (nome, costruttore, inizio_produzione) values ('Eclipse', 'Mitsubishi', 2010);
insert into modello (nome, costruttore, inizio_produzione) values ('H1', 'Hummer', 1998);
insert into modello (nome, costruttore, inizio_produzione) values ('MX-5', 'Mazda', 2011);
insert into modello (nome, costruttore, inizio_produzione) values ('Bonneville', 'Pontiac', 2005);
insert into modello (nome, costruttore, inizio_produzione) values ('A4', 'Audi', 2003);
insert into modello (nome, costruttore, inizio_produzione) values ('Ram 1500', 'Dodge', 2004);
insert into modello (nome, costruttore, inizio_produzione) values ('Savana 3500', 'GMC', 2007);
insert into modello (nome, costruttore, inizio_produzione) values ('Venture', 'Chevrolet', 2004);
insert into modello (nome, costruttore, inizio_produzione) values ('Yukon XL 2500', 'GMC', 2005);
insert into modello (nome, costruttore, inizio_produzione) values ('FX', 'Infiniti', 2010);
insert into modello (nome, costruttore, inizio_produzione) values ('Aero 8', 'Morgan', 2006);
insert into modello (nome, costruttore, inizio_produzione) values ('Century', 'Buick', 2003);
insert into modello (nome, costruttore, inizio_produzione) values ('Canyon', 'GMC', 2012);
insert into modello (nome, costruttore, inizio_produzione) values ('Grand Am', 'Pontiac', 2005);
insert into modello (nome, costruttore, inizio_produzione) values ('RX-8', 'Mazda', 2008);
insert into modello (nome, costruttore, inizio_produzione) values ('3 Series', 'BMW', 1996);
insert into modello (nome, costruttore, inizio_produzione) values ('Pilot', 'Honda', 2004);
insert into modello (nome, costruttore, inizio_produzione) values ('500', 'Fiat', 2012);
insert into modello (nome, costruttore, inizio_produzione) values ('Odyssey', 'Honda', 2008);
insert into modello (nome, costruttore, inizio_produzione) values ('Sonoma Club Coupe', 'GMC', 1998);
insert into modello (nome, costruttore, inizio_produzione) values ('Blazer', 'Chevrolet', 2000);
insert into modello (nome, costruttore, inizio_produzione) values ('Touareg', 'Volkswagen', 2006);
insert into modello (nome, costruttore, inizio_produzione) values ('Caprice Classic', 'Chevrolet', 1995);
insert into modello (nome, costruttore, inizio_produzione) values ('Pajero', 'Mitsubishi', 1989);
insert into modello (nome, costruttore, inizio_produzione) values ('Ascender', 'Isuzu', 2003);
insert into modello (nome, costruttore, inizio_produzione) values ('Freestar', 'Ford', 2007);
insert into modello (nome, costruttore, inizio_produzione) values ('Quest', 'Nissan', 1999);
insert into modello (nome, costruttore, inizio_produzione) values ('Suburban 1500', 'Chevrolet', 2005);
insert into modello (nome, costruttore, inizio_produzione) values ('Galant', 'Mitsubishi', 1998);
insert into modello (nome, costruttore, inizio_produzione) values ('SL-Class', 'Mercedes-Benz', 1986);
insert into modello (nome, costruttore, inizio_produzione) values ('B-Series Plus', 'Mazda', 2001);
insert into modello (nome, costruttore, inizio_produzione) values ('Firefly', 'Pontiac', 1994);
insert into modello (nome, costruttore, inizio_produzione) values ('7 Series', 'BMW', 2009);
insert into modello (nome, costruttore, inizio_produzione) values ('G-Class', 'Mercedes-Benz', 2002);
insert into modello (nome, costruttore, inizio_produzione) values ('Skylark', 'Buick', 1995);
insert into modello (nome, costruttore, inizio_produzione) values ('G5', 'Pontiac', 2009);
insert into modello (nome, costruttore, inizio_produzione) values ('Cougar', 'Mercury', 1968);
insert into modello (nome, costruttore, inizio_produzione) values ('Outlook', 'Saturn', 2009);
insert into modello (nome, costruttore, inizio_produzione) values ('EX', 'Infiniti', 2008);
insert into modello (nome, costruttore, inizio_produzione) values ('Vantage', 'Aston Martin', 2006);
insert into modello (nome, costruttore, inizio_produzione) values ('G', 'Infiniti', 1992);
insert into modello (nome, costruttore, inizio_produzione) values ('Savana 1500', 'GMC', 1998);
insert into modello (nome, costruttore, inizio_produzione) values ('Viper', 'Dodge', 1993);
insert into modello (nome, costruttore, inizio_produzione) values ('Evora', 'Lotus', 2011);
insert into modello (nome, costruttore, inizio_produzione) values ('RDX', 'Acura', 2012);
insert into modello (nome, costruttore, inizio_produzione) values ('5 Series', 'BMW', 1993);
insert into modello (nome, costruttore, inizio_produzione) values ('TL', 'Acura', 2004);
insert into modello (nome, costruttore, inizio_produzione) values ('Highlander', 'Toyota', 2004);
insert into modello (nome, costruttore, inizio_produzione) values ('Rally Wagon G2500', 'GMC', 1995);
insert into modello (nome, costruttore, inizio_produzione) values ('Altima', 'Nissan', 2005);
insert into modello (nome, costruttore, inizio_produzione) values ('Rio', 'Kia', 2009);
insert into modello (nome, costruttore, inizio_produzione) values ('Elise', 'Lotus', 2011);
insert into modello (nome, costruttore, inizio_produzione) values ('Econoline E250', 'Ford', 2001);
insert into modello (nome, costruttore, inizio_produzione) values ('S80', 'Volvo', 2001);
insert into modello (nome, costruttore, inizio_produzione) values ('350Z', 'Nissan', 2005);
insert into modello (nome, costruttore, inizio_produzione) values ('Titan', 'Nissan', 2011);
insert into modello (nome, costruttore, inizio_produzione) values ('Rodeo', 'Isuzu', 1993);
insert into modello (nome, costruttore, inizio_produzione) values ('Ion', 'Saturn', 2005);
insert into modello (nome, costruttore, inizio_produzione) values ('240SX', 'Nissan', 1992);
insert into modello (nome, costruttore, inizio_produzione) values ('Montero Sport', 'Mitsubishi', 2000);
insert into modello (nome, costruttore, inizio_produzione) values ('Passat', 'Volkswagen', 1997);
insert into modello (nome, costruttore, inizio_produzione) values ('90', 'Audi', 1994);
insert into modello (nome, costruttore, inizio_produzione) values ('Sonata', 'Hyundai', 2006);
insert into modello (nome, costruttore, inizio_produzione) values ('Dakota', 'Dodge', 2001);
insert into modello (nome, costruttore, inizio_produzione) values ('CLK-Class', 'Mercedes-Benz', 2008);
insert into modello (nome, costruttore, inizio_produzione) values ('Range Rover Sport', 'Land Rover', 2006);
insert into modello (nome, costruttore, inizio_produzione) values ('Topaz', 'Mercury', 1987);
insert into modello (nome, costruttore, inizio_produzione) values ('Tacoma Xtra', 'Toyota', 1997);
insert into modello (nome, costruttore, inizio_produzione) values ('Quattro', 'Audi', 1985);
insert into modello (nome, costruttore, inizio_produzione) values ('Cayman', 'Porsche', 2006);
insert into modello (nome, costruttore, inizio_produzione) values ('Town Car', 'Lincoln', 2007);
insert into modello (nome, costruttore, inizio_produzione) values ('Avenger', 'Dodge', 2010);
insert into modello (nome, costruttore, inizio_produzione) values ('Concorde', 'Chrysler', 1996);
insert into modello (nome, costruttore, inizio_produzione) values ('G-Series G30', 'Chevrolet', 1995);
insert into modello (nome, costruttore, inizio_produzione) values ('100', 'Audi', 1993);
insert into modello (nome, costruttore, inizio_produzione) values ('GTI', 'Volkswagen', 2003);
