insert into optional (nome, prezzo, categoria, fornitore) values ('Witting, Kertzmann and Boyle', 1473.63, 'Ardea golieth', 'Dodge');
insert into optional (nome, prezzo, categoria, fornitore) values ('Smith-Bergnaum', 2584.62, 'Coluber constrictor', 'Chevrolet');
insert into optional (nome, prezzo, categoria, fornitore) values ('Kub Inc', 1053.72, 'Raphicerus campestris', 'Plymouth');
insert into optional (nome, prezzo, categoria, fornitore) values ('Marvin-Keebler', 1922.35, 'Catharacta skua', 'Volvo');
insert into optional (nome, prezzo, categoria, fornitore) values ('Howell, Abernathy and Padberg', 8949.1, 'Falco peregrinus', 'Mercedes-Benz');
insert into optional (nome, prezzo, categoria, fornitore) values ('Walker, Botsford and Wyman', 6924.52, 'Larus dominicanus', 'Nissan');
insert into optional (nome, prezzo, categoria, fornitore) values ('Reynolds-Lueilwitz', 3451.74, 'Haematopus ater', 'Saab');
insert into optional (nome, prezzo, categoria, fornitore) values ('Tromp and Sons', 6097.56, 'Larus fuliginosus', 'Toyota');
insert into optional (nome, prezzo, categoria, fornitore) values ('Frami-Graham', 4458.89, 'Tursiops truncatus', 'Chrysler');
insert into optional (nome, prezzo, categoria, fornitore) values ('Mraz, Bergnaum and Bayer', 5259.99, 'Ciconia ciconia', 'Mercury');
insert into optional (nome, prezzo, categoria, fornitore) values ('Heller Inc', 4544.79, 'Cracticus nigroagularis', 'Pontiac');
insert into optional (nome, prezzo, categoria, fornitore) values ('Toy, Lueilwitz and Schmeler', 4937.87, 'Petaurus norfolcensis', 'Acura');
insert into optional (nome, prezzo, categoria, fornitore) values ('Herman Group', 2402.06, 'Lepus arcticus', 'Toyota');
insert into optional (nome, prezzo, categoria, fornitore) values ('Quitzon, Herman and Durgan', 793.11, 'Ceratotherium simum', 'Mitsubishi');
insert into optional (nome, prezzo, categoria, fornitore) values ('McLaughlin-Brakus', 2707.43, 'Microcebus murinus', 'Porsche');
insert into optional (nome, prezzo, categoria, fornitore) values ('Hintz and Sons', 9299.23, 'Meleagris gallopavo', 'Dodge');
insert into optional (nome, prezzo, categoria, fornitore) values ('Howe-Kovacek', 6639.42, 'Macropus giganteus', 'Pontiac');
insert into optional (nome, prezzo, categoria, fornitore) values ('Jast-Schamberger', 3940.59, 'Ursus maritimus', 'Buick');
insert into optional (nome, prezzo, categoria, fornitore) values ('Satterfield, Kemmer and Hamill', 1830.35, 'Anas punctata', 'Subaru');
insert into optional (nome, prezzo, categoria, fornitore) values ('Schneider LLC', 4032.22, 'Papio cynocephalus', 'Chrysler');
insert into optional (nome, prezzo, categoria, fornitore) values ('Goyette-Krajcik', 1913.62, 'Erinaceus frontalis', 'Lexus');
insert into optional (nome, prezzo, categoria, fornitore) values ('Cronin LLC', 3302.02, 'Cacatua tenuirostris', 'Mercury');
insert into optional (nome, prezzo, categoria, fornitore) values ('Hettinger and Sons', 728.02, 'Vulpes vulpes', 'Lexus');
insert into optional (nome, prezzo, categoria, fornitore) values ('MacGyver, Blanda and Bernhard', 3729.08, 'Erethizon dorsatum', 'GMC');
insert into optional (nome, prezzo, categoria, fornitore) values ('Kilback, Johns and Hyatt', 6140.51, 'Felis caracal', 'Bentley');
insert into optional (nome, prezzo, categoria, fornitore) values ('Windler Inc', 7780.83, 'Canis mesomelas', 'Dodge');
insert into optional (nome, prezzo, categoria, fornitore) values ('Schiller Inc', 490.27, 'Manouria emys', 'Ford');
insert into optional (nome, prezzo, categoria, fornitore) values ('Grant-Raynor', 2743.81, 'Cervus elaphus', 'Mitsubishi');
insert into optional (nome, prezzo, categoria, fornitore) values ('Watsica, O''Connell and Schmitt', 4882.85, 'Felis silvestris lybica', 'Buick');
insert into optional (nome, prezzo, categoria, fornitore) values ('O''Reilly and Sons', 3620.74, 'unavailable', 'Ford');
insert into optional (nome, prezzo, categoria, fornitore) values ('Quigley-Konopelski', 9033.28, 'Vombatus ursinus', 'Ford');
insert into optional (nome, prezzo, categoria, fornitore) values ('Erdman-Cartwright', 2336.49, 'Spermophilus richardsonii', 'Audi');
insert into optional (nome, prezzo, categoria, fornitore) values ('McClure-Welch', 4497.7, 'unavailable', 'GMC');
insert into optional (nome, prezzo, categoria, fornitore) values ('Wunsch, Rohan and Quitzon', 5116.83, 'Manouria emys', 'Saab');
insert into optional (nome, prezzo, categoria, fornitore) values ('Kirlin-Reilly', 7624.68, 'Macropus giganteus', 'Isuzu');
insert into optional (nome, prezzo, categoria, fornitore) values ('Tillman-Wilkinson', 3291.65, 'Kobus defassa', 'Mazda');
insert into optional (nome, prezzo, categoria, fornitore) values ('Olson-Weimann', 4031.43, 'Libellula quadrimaculata', 'Mitsubishi');
insert into optional (nome, prezzo, categoria, fornitore) values ('King-Jacobi', 9728.11, 'Mabuya spilogaster', 'Maybach');
insert into optional (nome, prezzo, categoria, fornitore) values ('Goodwin, Satterfield and Robel', 6386.18, 'Butorides striatus', 'Pontiac');
insert into optional (nome, prezzo, categoria, fornitore) values ('McCullough-Upton', 4540.03, 'Ovis dalli stonei', 'Mercedes-Benz');
insert into optional (nome, prezzo, categoria, fornitore) values ('Barrows, Hintz and Adams', 353.88, 'Macropus robustus', 'Lotus');
insert into optional (nome, prezzo, categoria, fornitore) values ('Kling, Powlowski and Howe', 5238.8, 'Tayassu pecari', 'Dodge');
insert into optional (nome, prezzo, categoria, fornitore) values ('Lehner-Ward', 7484.78, 'Rangifer tarandus', 'Mercedes-Benz');
insert into optional (nome, prezzo, categoria, fornitore) values ('Gibson-Crist', 6712.39, 'Marmota monax', 'Chevrolet');
insert into optional (nome, prezzo, categoria, fornitore) values ('Hessel Inc', 6296.75, 'Gopherus agassizii', 'Mitsubishi');
insert into optional (nome, prezzo, categoria, fornitore) values ('Bode Inc', 6781.99, 'Pseudoleistes virescens', 'Mercedes-Benz');
insert into optional (nome, prezzo, categoria, fornitore) values ('Marks, Bode and Graham', 7092.07, 'Spermophilus tridecemlineatus', 'Cadillac');
insert into optional (nome, prezzo, categoria, fornitore) values ('McGlynn Group', 3980.69, 'Charadrius tricollaris', 'Suzuki');
insert into optional (nome, prezzo, categoria, fornitore) values ('Johnson-King', 7967.17, 'Manouria emys', 'Toyota');
insert into optional (nome, prezzo, categoria, fornitore) values ('Mann, Schuster and Rippin', 4396.44, 'Lycaon pictus', 'Jeep');
insert into optional (nome, prezzo, categoria, fornitore) values ('Orn-Walter', 6939.02, 'unavailable', 'Plymouth');
insert into optional (nome, prezzo, categoria, fornitore) values ('Kautzer, Gutkowski and Lynch', 606.91, 'Sagittarius serpentarius', 'BMW');
insert into optional (nome, prezzo, categoria, fornitore) values ('Hodkiewicz, Heller and Hayes', 2175.64, 'Anastomus oscitans', 'Mitsubishi');
insert into optional (nome, prezzo, categoria, fornitore) values ('Bergnaum-Marvin', 311.46, 'Dendrocitta vagabunda', 'Mercedes-Benz');
insert into optional (nome, prezzo, categoria, fornitore) values ('Kessler, Aufderhar and Mayert', 5068.5, 'Tetracerus quadricornis', 'Chevrolet');
insert into optional (nome, prezzo, categoria, fornitore) values ('Halvorson-Upton', 7815.0, 'Speothos vanaticus', 'Isuzu');
insert into optional (nome, prezzo, categoria, fornitore) values ('Thompson, Schowalter and Waelchi', 7036.9, 'Eunectes sp.', 'Aston Martin');
insert into optional (nome, prezzo, categoria, fornitore) values ('Price, Ledner and Grady', 9941.51, 'Ardea cinerea', 'Land Rover');
insert into optional (nome, prezzo, categoria, fornitore) values ('Sporer, Sporer and Jakubowski', 1594.33, 'Phasianus colchicus', 'Cadillac');
insert into optional (nome, prezzo, categoria, fornitore) values ('Prohaska, Mills and Beahan', 5549.07, 'Phalaropus fulicarius', 'Jeep');
insert into optional (nome, prezzo, categoria, fornitore) values ('Hartmann, Kub and Hauck', 4690.91, 'Larus fuliginosus', 'Chevrolet');
insert into optional (nome, prezzo, categoria, fornitore) values ('O''Hara Group', 985.93, 'Lepus arcticus', 'Honda');
insert into optional (nome, prezzo, categoria, fornitore) values ('Feeney, Fritsch and Waelchi', 2840.49, 'Spilogale gracilis', 'BMW');
insert into optional (nome, prezzo, categoria, fornitore) values ('Conn-McGlynn', 9716.96, 'Ninox superciliaris', 'GMC');
insert into optional (nome, prezzo, categoria, fornitore) values ('Thiel and Sons', 6639.05, 'Grus rubicundus', 'Land Rover');
insert into optional (nome, prezzo, categoria, fornitore) values ('Schultz, Gleason and Bashirian', 3189.87, 'Bison bison', 'Ford');
insert into optional (nome, prezzo, categoria, fornitore) values ('Runte, Bashirian and Kihn', 8773.58, 'Tringa glareola', 'Chevrolet');
insert into optional (nome, prezzo, categoria, fornitore) values ('Heidenreich-Torphy', 6318.75, 'Anthropoides paradisea', 'Hyundai');
insert into optional (nome, prezzo, categoria, fornitore) values ('Mitchell, Kshlerin and Howe', 4359.61, 'Paraxerus cepapi', 'Studebaker');
insert into optional (nome, prezzo, categoria, fornitore) values ('Wintheiser, Gaylord and Fadel', 708.78, 'Myrmecophaga tridactyla', 'Pontiac');
insert into optional (nome, prezzo, categoria, fornitore) values ('D''Amore Inc', 8627.3, 'Spizaetus coronatus', 'Kia');
insert into optional (nome, prezzo, categoria, fornitore) values ('Schuster Inc', 9241.41, 'Cochlearius cochlearius', 'Isuzu');
insert into optional (nome, prezzo, categoria, fornitore) values ('Effertz LLC', 5320.37, 'Cochlearius cochlearius', 'Audi');
insert into optional (nome, prezzo, categoria, fornitore) values ('Torp, Smith and Bernhard', 1550.38, 'Cynictis penicillata', 'Eagle');
insert into optional (nome, prezzo, categoria, fornitore) values ('Mosciski, Rogahn and Langosh', 9314.14, 'unavailable', 'Oldsmobile');
insert into optional (nome, prezzo, categoria, fornitore) values ('Bogan, Abbott and Olson', 5259.99, 'Ceratotherium simum', 'Maybach');
insert into optional (nome, prezzo, categoria, fornitore) values ('Pouros, Powlowski and Vandervort', 2098.01, 'Erinaceus frontalis', 'Bentley');
insert into optional (nome, prezzo, categoria, fornitore) values ('Paucek Inc', 5922.7, 'Aonyx cinerea', 'Porsche');
insert into optional (nome, prezzo, categoria, fornitore) values ('Kshlerin, Feil and Nienow', 6658.56, 'Lycosa godeffroyi', 'BMW');
insert into optional (nome, prezzo, categoria, fornitore) values ('Deckow, Cremin and Luettgen', 8403.48, 'Paroaria gularis', 'Porsche');
insert into optional (nome, prezzo, categoria, fornitore) values ('Schulist, Ruecker and Kertzmann', 9799.83, 'Haematopus ater', 'Dodge');
insert into optional (nome, prezzo, categoria, fornitore) values ('Hyatt, Kemmer and Quitzon', 3332.85, 'Bassariscus astutus', 'Toyota');
insert into optional (nome, prezzo, categoria, fornitore) values ('Wolf Inc', 470.1, 'Limosa haemastica', 'Pontiac');
insert into optional (nome, prezzo, categoria, fornitore) values ('Runolfsson Group', 1824.59, 'Lorythaixoides concolor', 'Jeep');
insert into optional (nome, prezzo, categoria, fornitore) values ('Kohler-Rowe', 7490.6, 'Phasianus colchicus', 'Lexus');
insert into optional (nome, prezzo, categoria, fornitore) values ('Kshlerin, Renner and Kohler', 1014.25, 'Macropus eugenii', 'GMC');
insert into optional (nome, prezzo, categoria, fornitore) values ('Kunze Inc', 123.29, 'Hymenolaimus malacorhynchus', 'Ford');
insert into optional (nome, prezzo, categoria, fornitore) values ('Heller LLC', 9806.59, 'Felis chaus', 'Suzuki');
insert into optional (nome, prezzo, categoria, fornitore) values ('Harris, Corkery and Spinka', 5142.41, 'Nucifraga columbiana', 'Hummer');
insert into optional (nome, prezzo, categoria, fornitore) values ('Hills Inc', 172.51, 'Graspus graspus', 'Pontiac');
insert into optional (nome, prezzo, categoria, fornitore) values ('Upton Inc', 2079.5, 'Butorides striatus', 'GMC');
insert into optional (nome, prezzo, categoria, fornitore) values ('Kris Group', 2103.86, 'Buteo galapagoensis', 'Cadillac');
insert into optional (nome, prezzo, categoria, fornitore) values ('McCullough-Tillman', 5136.67, 'Phalaropus lobatus', 'Pontiac');
insert into optional (nome, prezzo, categoria, fornitore) values ('Volkman-Altenwerth', 6304.58, 'Eurocephalus anguitimens', 'Mitsubishi');
insert into optional (nome, prezzo, categoria, fornitore) values ('Considine-Krajcik', 4140.22, 'Diomedea irrorata', 'Mitsubishi');
insert into optional (nome, prezzo, categoria, fornitore) values ('Stanton-Schaefer', 2257.1, 'Acinynox jubatus', 'Hyundai');
insert into optional (nome, prezzo, categoria, fornitore) values ('Fritsch Group', 8911.87, 'Coluber constrictor', 'Jaguar');
insert into optional (nome, prezzo, categoria, fornitore) values ('Reinger, Walker and Gerhold', 8135.63, 'Uraeginthus angolensis', 'Mazda');
insert into optional (nome, prezzo, categoria, fornitore) values ('Lueilwitz Inc', 5532.99, 'Hyaena brunnea', 'Mercedes-Benz');
insert into optional (nome, prezzo, categoria, fornitore) values ('Emmerich Group', 5325.65, 'Dipodomys deserti', 'Lincoln');
