insert into sede (id, tipo, nazione, città, via, civico) values (1, 'Concessionario', 'Greece', 'Ágios Matthaíos', 'Clyde Gallagher', '3');
insert into sede (id, tipo, nazione, città, via, civico) values (2, 'Officina', 'Portugal', 'Silgueiros', 'Lillian', '277');
insert into sede (id, tipo, nazione, città, via, civico) values (3, 'Concessionario', 'Ukraine', 'Savran’', 'Elka', '774');
insert into sede (id, tipo, nazione, città, via, civico) values (4, 'Concessionario', 'Philippines', 'Esperanza', 'Boyd', '239');
insert into sede (id, tipo, nazione, città, via, civico) values (5, 'Officina', 'Portugal', 'Vila do Bispo', 'Village Green', '971');
insert into sede (id, tipo, nazione, città, via, civico) values (6, 'Officina', 'Argentina', 'Basail', 'Sauthoff', '76048');
insert into sede (id, tipo, nazione, città, via, civico) values (7, 'Concessionario', 'Vietnam', 'Đắk Mâm', 'Mccormick', '7689');
insert into sede (id, tipo, nazione, città, via, civico) values (8, 'Officina', 'Syria', 'Ar Raqqah', 'Transport', '1655');
insert into sede (id, tipo, nazione, città, via, civico) values (9, 'Concessionario', 'Nigeria', 'Dankama', 'Roxbury', '4752');
insert into sede (id, tipo, nazione, città, via, civico) values (10, 'Officina', 'Ukraine', 'Voyinka', 'Bonner', '0017');
insert into sede (id, tipo, nazione, città, via, civico) values (11, 'Officina', 'China', 'Huocheng', 'Weeping Birch', '09');
insert into sede (id, tipo, nazione, città, via, civico) values (12, 'Concessionario', 'China', 'Yuekou', 'Mesta', '88138');
insert into sede (id, tipo, nazione, città, via, civico) values (13, 'Concessionario', 'Sweden', 'Karlstad', 'Eliot', '653');
insert into sede (id, tipo, nazione, città, via, civico) values (14, 'Concessionario', 'Indonesia', 'Purworejo', 'Clarendon', '10922');
insert into sede (id, tipo, nazione, città, via, civico) values (15, 'Officina', 'El Salvador', 'Santiago de María', 'Nancy', '55427');
insert into sede (id, tipo, nazione, città, via, civico) values (16, 'Concessionario', 'Croatia', 'Laslovo', 'Esker', '51');
insert into sede (id, tipo, nazione, città, via, civico) values (17, 'Concessionario', 'China', 'Xiaping', 'Northport', '9');
insert into sede (id, tipo, nazione, città, via, civico) values (18, 'Concessionario', 'China', 'Dajing', 'Lillian', '891');
insert into sede (id, tipo, nazione, città, via, civico) values (19, 'Officina', 'Russia', 'Nelidovo', 'Lotheville', '79388');
insert into sede (id, tipo, nazione, città, via, civico) values (20, 'Officina', 'Portugal', 'Ferreira do Zêzere', '3rd', '861');
insert into sede (id, tipo, nazione, città, via, civico) values (21, 'Officina', 'Honduras', 'Cane', 'Packers', '15279');
insert into sede (id, tipo, nazione, città, via, civico) values (22, 'Concessionario', 'France', 'Montreuil', 'Ryan', '2390');
insert into sede (id, tipo, nazione, città, via, civico) values (23, 'Concessionario', 'Czech Republic', 'Čejkovice', 'Pearson', '022');
insert into sede (id, tipo, nazione, città, via, civico) values (24, 'Concessionario', 'Philippines', 'Cabagan', 'Scofield', '11568');
insert into sede (id, tipo, nazione, città, via, civico) values (25, 'Concessionario', 'France', 'Domont', 'Gateway', '66');
insert into sede (id, tipo, nazione, città, via, civico) values (26, 'Concessionario', 'Brazil', 'Mogi Guaçu', 'Vidon', '02');
insert into sede (id, tipo, nazione, città, via, civico) values (27, 'Concessionario', 'Slovenia', 'Morje', 'Gina', '64103');
insert into sede (id, tipo, nazione, città, via, civico) values (28, 'Officina', 'South Africa', 'Thaba Nchu', 'Old Shore', '5418');
insert into sede (id, tipo, nazione, città, via, civico) values (29, 'Officina', 'Venezuela', 'Lagunillas', 'Cottonwood', '63');
insert into sede (id, tipo, nazione, città, via, civico) values (30, 'Concessionario', 'Vietnam', 'Bộc Bố', 'Carberry', '79433');
insert into sede (id, tipo, nazione, città, via, civico) values (31, 'Concessionario', 'China', 'Zhangping', 'Katie', '44');
insert into sede (id, tipo, nazione, città, via, civico) values (32, 'Concessionario', 'Argentina', 'Saladas', 'Sunnyside', '43');
insert into sede (id, tipo, nazione, città, via, civico) values (33, 'Officina', 'Russia', 'Ursk', 'Maple Wood', '5000');
insert into sede (id, tipo, nazione, città, via, civico) values (34, 'Concessionario', 'Mongolia', 'Har-Us', '1st', '41297');
insert into sede (id, tipo, nazione, città, via, civico) values (35, 'Concessionario', 'Philippines', 'Balangkayan', 'Helena', '76');
insert into sede (id, tipo, nazione, città, via, civico) values (36, 'Concessionario', 'Israel', 'Qiryat Motzkin', 'Hanover', '5');
insert into sede (id, tipo, nazione, città, via, civico) values (37, 'Officina', 'France', 'Niort', 'Hooker', '535');
insert into sede (id, tipo, nazione, città, via, civico) values (38, 'Officina', 'China', 'Pubu', 'Merry', '5835');
insert into sede (id, tipo, nazione, città, via, civico) values (39, 'Concessionario', 'Ireland', 'Old Kilcullen', 'Hermina', '504');
insert into sede (id, tipo, nazione, città, via, civico) values (40, 'Officina', 'China', 'Leyuan', 'Toban', '8942');
insert into sede (id, tipo, nazione, città, via, civico) values (41, 'Officina', 'Indonesia', 'Sukodono', 'Kings', '273');
insert into sede (id, tipo, nazione, città, via, civico) values (42, 'Officina', 'China', 'Taozhou', 'Commercial', '06410');
insert into sede (id, tipo, nazione, città, via, civico) values (43, 'Concessionario', 'China', 'Nanyang', 'Steensland', '7506');
insert into sede (id, tipo, nazione, città, via, civico) values (44, 'Officina', 'Croatia', 'Zagreb - Centar', 'Aberg', '92');
insert into sede (id, tipo, nazione, città, via, civico) values (45, 'Officina', 'China', 'Meijiahe', 'Debra', '295');
insert into sede (id, tipo, nazione, città, via, civico) values (46, 'Concessionario', 'Afghanistan', 'Rustāq', 'Vermont', '66687');
insert into sede (id, tipo, nazione, città, via, civico) values (47, 'Concessionario', 'China', 'Sandaotong', 'American Ash', '5');
insert into sede (id, tipo, nazione, città, via, civico) values (48, 'Officina', 'China', 'Kuandian', 'Twin Pines', '27723');
insert into sede (id, tipo, nazione, città, via, civico) values (49, 'Concessionario', 'Sweden', 'Tullinge', 'Carey', '2509');
insert into sede (id, tipo, nazione, città, via, civico) values (50, 'Concessionario', 'Kosovo', 'Lloqan', 'Lakewood Gardens', '8');
insert into sede (id, tipo, nazione, città, via, civico) values (51, 'Officina', 'Indonesia', 'Samburat', 'Arrowood', '5129');
insert into sede (id, tipo, nazione, città, via, civico) values (52, 'Officina', 'Indonesia', 'Palopat', 'Susan', '91129');
insert into sede (id, tipo, nazione, città, via, civico) values (53, 'Concessionario', 'China', 'Yongfeng', 'Walton', '0056');
insert into sede (id, tipo, nazione, città, via, civico) values (54, 'Officina', 'Thailand', 'Kut Rang', 'Goodland', '0');
insert into sede (id, tipo, nazione, città, via, civico) values (55, 'Officina', 'Japan', 'Chiryū', 'Lien', '09');
insert into sede (id, tipo, nazione, città, via, civico) values (56, 'Officina', 'China', 'Qingtaiping', 'Scoville', '3312');
insert into sede (id, tipo, nazione, città, via, civico) values (57, 'Concessionario', 'Russia', 'Zmiyëvka', 'Walton', '382');
insert into sede (id, tipo, nazione, città, via, civico) values (58, 'Officina', 'Poland', 'Kozy', 'Debs', '21154');
insert into sede (id, tipo, nazione, città, via, civico) values (59, 'Concessionario', 'Japan', 'Katori-shi', 'Larry', '6');
insert into sede (id, tipo, nazione, città, via, civico) values (60, 'Officina', 'China', 'Shangping', 'Vermont', '6');
insert into sede (id, tipo, nazione, città, via, civico) values (61, 'Officina', 'China', 'Yalukou', 'Gateway', '7662');
insert into sede (id, tipo, nazione, città, via, civico) values (62, 'Concessionario', 'Afghanistan', 'Mardīān', 'Aberg', '85672');
insert into sede (id, tipo, nazione, città, via, civico) values (63, 'Concessionario', 'Indonesia', 'Rangah', 'Golf View', '747');
insert into sede (id, tipo, nazione, città, via, civico) values (64, 'Concessionario', 'Portugal', 'Casais de Vera Cruz', 'Corben', '5416');
insert into sede (id, tipo, nazione, città, via, civico) values (65, 'Concessionario', 'China', 'Huzhuang', 'Commercial', '6277');
insert into sede (id, tipo, nazione, città, via, civico) values (66, 'Officina', 'Botswana', 'Gaborone', 'Killdeer', '98');
insert into sede (id, tipo, nazione, città, via, civico) values (67, 'Officina', 'Brazil', 'Arcos', 'Thackeray', '39');
insert into sede (id, tipo, nazione, città, via, civico) values (68, 'Officina', 'Philippines', 'Bagumbayan', 'Briar Crest', '1622');
insert into sede (id, tipo, nazione, città, via, civico) values (69, 'Concessionario', 'Brazil', 'Cosmópolis', 'Sachtjen', '79447');
insert into sede (id, tipo, nazione, città, via, civico) values (70, 'Concessionario', 'Poland', 'Przodkowo', 'Redwing', '5');
insert into sede (id, tipo, nazione, città, via, civico) values (71, 'Concessionario', 'Indonesia', 'Tawangsari', 'Burning Wood', '1');
insert into sede (id, tipo, nazione, città, via, civico) values (72, 'Officina', 'Guinea', 'Coyah', 'Stang', '8634');
insert into sede (id, tipo, nazione, città, via, civico) values (73, 'Officina', 'United States', 'Washington', 'Bonner', '60');
insert into sede (id, tipo, nazione, città, via, civico) values (74, 'Officina', 'Portugal', 'Fornelos', 'Lotheville', '7276');
insert into sede (id, tipo, nazione, città, via, civico) values (75, 'Concessionario', 'Russia', 'Ostankinskiy', 'Redwing', '1');
insert into sede (id, tipo, nazione, città, via, civico) values (76, 'Concessionario', 'Indonesia', 'Cipondok', 'Debs', '0');
insert into sede (id, tipo, nazione, città, via, civico) values (77, 'Officina', 'Philippines', 'Pandakan', 'Scofield', '8');
insert into sede (id, tipo, nazione, città, via, civico) values (78, 'Officina', 'Ukraine', 'Uhlove', 'Del Sol', '2');
insert into sede (id, tipo, nazione, città, via, civico) values (79, 'Concessionario', 'Uruguay', 'Santa Catalina', 'Scott', '8415');
insert into sede (id, tipo, nazione, città, via, civico) values (80, 'Officina', 'Peru', 'Jauja', 'Lakewood', '69447');
insert into sede (id, tipo, nazione, città, via, civico) values (81, 'Officina', 'China', 'Longshan', 'Armistice', '37');
insert into sede (id, tipo, nazione, città, via, civico) values (82, 'Officina', 'Sweden', 'Söderhamn', 'Pine View', '2');
insert into sede (id, tipo, nazione, città, via, civico) values (83, 'Concessionario', 'China', 'Lianjiangkou', 'Arrowood', '2457');
insert into sede (id, tipo, nazione, città, via, civico) values (84, 'Concessionario', 'China', 'Haoyi', '5th', '11991');
insert into sede (id, tipo, nazione, città, via, civico) values (85, 'Officina', 'Philippines', 'Tibigan', 'Glendale', '893');
insert into sede (id, tipo, nazione, città, via, civico) values (86, 'Concessionario', 'Russia', 'Mnogoudobnoye', 'Buena Vista', '468');
insert into sede (id, tipo, nazione, città, via, civico) values (87, 'Officina', 'Bangladesh', 'Mādārīpur', 'Sullivan', '7');
insert into sede (id, tipo, nazione, città, via, civico) values (88, 'Officina', 'Andorra', 'Canillo', 'Everett', '2');
insert into sede (id, tipo, nazione, città, via, civico) values (89, 'Officina', 'Mozambique', 'Xai-Xai', 'Lakewood', '7');
insert into sede (id, tipo, nazione, città, via, civico) values (90, 'Officina', 'Indonesia', 'Kampunglistrik', 'Brickson Park', '4');
insert into sede (id, tipo, nazione, città, via, civico) values (91, 'Concessionario', 'Thailand', 'Betong', 'Nelson', '21552');
insert into sede (id, tipo, nazione, città, via, civico) values (92, 'Concessionario', 'Slovenia', 'Ankaran', 'Mayer', '75412');
insert into sede (id, tipo, nazione, città, via, civico) values (93, 'Concessionario', 'Russia', 'Magistral’nyy', 'Emmet', '8411');
insert into sede (id, tipo, nazione, città, via, civico) values (94, 'Concessionario', 'Argentina', 'Belén de Escobar', '1st', '585');
insert into sede (id, tipo, nazione, città, via, civico) values (95, 'Officina', 'China', 'Baoshan', 'Division', '001');
insert into sede (id, tipo, nazione, città, via, civico) values (96, 'Officina', 'Indonesia', 'Nangabere', 'Kenwood', '17781');
insert into sede (id, tipo, nazione, città, via, civico) values (97, 'Concessionario', 'Philippines', 'Bagumbayan', 'Fallview', '78');
insert into sede (id, tipo, nazione, città, via, civico) values (98, 'Officina', 'China', 'Chidian', 'Donald', '023');
insert into sede (id, tipo, nazione, città, via, civico) values (99, 'Concessionario', 'France', 'Aix-en-Provence', 'Pawling', '434');
insert into sede (id, tipo, nazione, città, via, civico) values (100, 'Concessionario', 'Japan', 'Nyūzen', 'Cascade', '7654');